# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7vx690tffg1761-2

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/sakthi/lib_convnet/RIFFA_BUILDER/user/Output/FPGA_PRJ/prj/VC709_Gen3x4If128.cache/wt [current_project]
set_property parent.project_path /home/sakthi/lib_convnet/RIFFA_BUILDER/user/Output/FPGA_PRJ/prj/VC709_Gen3x4If128.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part xilinx.com:vc709:part0:1.5 [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
read_ip /home/sakthi/lib_convnet/RIFFA_BUILDER/user/Output/FPGA_PRJ/ip/PCIeGen3x4If128.xci
set_property used_in_implementation false [get_files -all /home/sakthi/lib_convnet/RIFFA_BUILDER/user/Output/FPGA_PRJ/ip/PCIeGen3x4If128.dcp]
set_property is_locked true [get_files /home/sakthi/lib_convnet/RIFFA_BUILDER/user/Output/FPGA_PRJ/ip/PCIeGen3x4If128.xci]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
synth_design -top PCIeGen3x4If128 -part xc7vx690tffg1761-2 -mode out_of_context
rename_ref -prefix_all PCIeGen3x4If128_
write_checkpoint -noxdef PCIeGen3x4If128.dcp
catch { report_utilization -file PCIeGen3x4If128_utilization_synth.rpt -pb PCIeGen3x4If128_utilization_synth.pb }
if { [catch {
  file copy -force /home/sakthi/lib_convnet/RIFFA_BUILDER/user/Output/FPGA_PRJ/prj/VC709_Gen3x4If128.runs/PCIeGen3x4If128_synth_1/PCIeGen3x4If128.dcp /home/sakthi/lib_convnet/RIFFA_BUILDER/user/Output/FPGA_PRJ/ip/PCIeGen3x4If128.dcp
} _RESULT ] } { 
  send_msg_id runtcl-3 error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
  error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
}
if { [catch {
  write_verilog -force -mode synth_stub /home/sakthi/lib_convnet/RIFFA_BUILDER/user/Output/FPGA_PRJ/ip/PCIeGen3x4If128_stub.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a Verilog synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}
if { [catch {
  write_vhdl -force -mode synth_stub /home/sakthi/lib_convnet/RIFFA_BUILDER/user/Output/FPGA_PRJ/ip/PCIeGen3x4If128_stub.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a VHDL synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}
if { [catch {
  write_verilog -force -mode funcsim /home/sakthi/lib_convnet/RIFFA_BUILDER/user/Output/FPGA_PRJ/ip/PCIeGen3x4If128_sim_netlist.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the Verilog functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}
if { [catch {
  write_vhdl -force -mode funcsim /home/sakthi/lib_convnet/RIFFA_BUILDER/user/Output/FPGA_PRJ/ip/PCIeGen3x4If128_sim_netlist.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the VHDL functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if {[file isdir /home/sakthi/lib_convnet/RIFFA_BUILDER/user/Output/FPGA_PRJ/prj/VC709_Gen3x4If128.ip_user_files/ip/PCIeGen3x4If128]} {
  catch { 
    file copy -force /home/sakthi/lib_convnet/RIFFA_BUILDER/user/Output/FPGA_PRJ/ip/PCIeGen3x4If128_stub.v /home/sakthi/lib_convnet/RIFFA_BUILDER/user/Output/FPGA_PRJ/prj/VC709_Gen3x4If128.ip_user_files/ip/PCIeGen3x4If128
  }
}

if {[file isdir /home/sakthi/lib_convnet/RIFFA_BUILDER/user/Output/FPGA_PRJ/prj/VC709_Gen3x4If128.ip_user_files/ip/PCIeGen3x4If128]} {
  catch { 
    file copy -force /home/sakthi/lib_convnet/RIFFA_BUILDER/user/Output/FPGA_PRJ/ip/PCIeGen3x4If128_stub.vhdl /home/sakthi/lib_convnet/RIFFA_BUILDER/user/Output/FPGA_PRJ/prj/VC709_Gen3x4If128.ip_user_files/ip/PCIeGen3x4If128
  }
}
