// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.4
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ==============================================================

#ifndef __inference_conv2d_2_f2_4_3_1_H__
#define __inference_conv2d_2_f2_4_3_1_H__


#include <systemc>
using namespace sc_core;
using namespace sc_dt;




#include <iostream>
#include <fstream>

struct inference_conv2d_2_f2_4_3_1_ram : public sc_core::sc_module {

  static const unsigned DataWidth = 32;
  static const unsigned AddressRange = 16;
  static const unsigned AddressWidth = 4;

//latency = 1
//input_reg = 1
//output_reg = 0
sc_core::sc_in <sc_lv<AddressWidth> > address0;
sc_core::sc_in <sc_logic> ce0;
sc_core::sc_out <sc_lv<DataWidth> > q0;
sc_core::sc_in<sc_logic> reset;
sc_core::sc_in<bool> clk;


sc_lv<DataWidth> ram[AddressRange];


   SC_CTOR(inference_conv2d_2_f2_4_3_1_ram) {
        ram[0] = "0b00111101010011110000001100111110";
        ram[1] = "0b10111101010111101111010001100111";
        ram[2] = "0b00111101111001010010110101100110";
        ram[3] = "0b00111101101110001110010011000110";
        ram[4] = "0b00111101100111110000000111010011";
        ram[5] = "0b10111101101001011110011001000100";
        ram[6] = "0b10111101011110100111111010000001";
        ram[7] = "0b10111101110100100000100111101110";
        ram[8] = "0b10111101111010000001000000011111";
        ram[9] = "0b00111100000100011110101000011000";
        ram[10] = "0b10111101000011000011011010001010";
        ram[11] = "0b00111101100000110100010011000011";
        ram[12] = "0b10111101010100010101100010111000";
        ram[13] = "0b00111101011111001011000100101100";
        ram[14] = "0b10111110000010011100010110100100";
        ram[15] = "0b00111100100111001101110000001111";


SC_METHOD(prc_write_0);
  sensitive<<clk.pos();
   }


void prc_write_0()
{
    if (ce0.read() == sc_dt::Log_1) 
    {
            if(address0.read().is_01() && address0.read().to_uint()<AddressRange)
              q0 = ram[address0.read().to_uint()];
            else
              q0 = sc_lv<DataWidth>();
    }
}


}; //endmodule


SC_MODULE(inference_conv2d_2_f2_4_3_1) {


static const unsigned DataWidth = 32;
static const unsigned AddressRange = 16;
static const unsigned AddressWidth = 4;

sc_core::sc_in <sc_lv<AddressWidth> > address0;
sc_core::sc_in<sc_logic> ce0;
sc_core::sc_out <sc_lv<DataWidth> > q0;
sc_core::sc_in<sc_logic> reset;
sc_core::sc_in<bool> clk;


inference_conv2d_2_f2_4_3_1_ram* meminst;


SC_CTOR(inference_conv2d_2_f2_4_3_1) {
meminst = new inference_conv2d_2_f2_4_3_1_ram("inference_conv2d_2_f2_4_3_1_ram");
meminst->address0(address0);
meminst->ce0(ce0);
meminst->q0(q0);

meminst->reset(reset);
meminst->clk(clk);
}
~inference_conv2d_2_f2_4_3_1() {
    delete meminst;
}


};//endmodule
#endif
