// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.4
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ==============================================================

#ifndef __inference_conv2d_2_f2_3_3_0_H__
#define __inference_conv2d_2_f2_3_3_0_H__


#include <systemc>
using namespace sc_core;
using namespace sc_dt;




#include <iostream>
#include <fstream>

struct inference_conv2d_2_f2_3_3_0_ram : public sc_core::sc_module {

  static const unsigned DataWidth = 32;
  static const unsigned AddressRange = 16;
  static const unsigned AddressWidth = 4;

//latency = 1
//input_reg = 1
//output_reg = 0
sc_core::sc_in <sc_lv<AddressWidth> > address0;
sc_core::sc_in <sc_logic> ce0;
sc_core::sc_out <sc_lv<DataWidth> > q0;
sc_core::sc_in<sc_logic> reset;
sc_core::sc_in<bool> clk;


sc_lv<DataWidth> ram[AddressRange];


   SC_CTOR(inference_conv2d_2_f2_3_3_0_ram) {
        ram[0] = "0b10111110001000101011111110011000";
        ram[1] = "0b10111100111011101101011011100011";
        ram[2] = "0b00111110001000000001101000110111";
        ram[3] = "0b00111100011111100011110111110100";
        ram[4] = "0b10111101110000111100101110001111";
        ram[5] = "0b10111110100000101000111001010000";
        ram[6] = "0b10111101010110110010010001001001";
        ram[7] = "0b10111110000110011110011001101000";
        ram[8] = "0b00111110011010001100100011101111";
        ram[9] = "0b00111110000000001011111000001110";
        ram[10] = "0b10111101000111000010010001110011";
        ram[11] = "0b10111101011000000110110111111111";
        ram[12] = "0b00111101001010011000011110011110";
        ram[13] = "0b00111100111100001001110000010101";
        ram[14] = "0b00111101111100010011000101100110";
        ram[15] = "0b00111101101011101001011000110000";


SC_METHOD(prc_write_0);
  sensitive<<clk.pos();
   }


void prc_write_0()
{
    if (ce0.read() == sc_dt::Log_1) 
    {
            if(address0.read().is_01() && address0.read().to_uint()<AddressRange)
              q0 = ram[address0.read().to_uint()];
            else
              q0 = sc_lv<DataWidth>();
    }
}


}; //endmodule


SC_MODULE(inference_conv2d_2_f2_3_3_0) {


static const unsigned DataWidth = 32;
static const unsigned AddressRange = 16;
static const unsigned AddressWidth = 4;

sc_core::sc_in <sc_lv<AddressWidth> > address0;
sc_core::sc_in<sc_logic> ce0;
sc_core::sc_out <sc_lv<DataWidth> > q0;
sc_core::sc_in<sc_logic> reset;
sc_core::sc_in<bool> clk;


inference_conv2d_2_f2_3_3_0_ram* meminst;


SC_CTOR(inference_conv2d_2_f2_3_3_0) {
meminst = new inference_conv2d_2_f2_3_3_0_ram("inference_conv2d_2_f2_3_3_0_ram");
meminst->address0(address0);
meminst->ce0(ce0);
meminst->q0(q0);

meminst->reset(reset);
meminst->clk(clk);
}
~inference_conv2d_2_f2_3_3_0() {
    delete meminst;
}


};//endmodule
#endif
