// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.4
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ==============================================================

#ifndef __inference_conv2d_2_f2_1_4_2_H__
#define __inference_conv2d_2_f2_1_4_2_H__


#include <systemc>
using namespace sc_core;
using namespace sc_dt;




#include <iostream>
#include <fstream>

struct inference_conv2d_2_f2_1_4_2_ram : public sc_core::sc_module {

  static const unsigned DataWidth = 32;
  static const unsigned AddressRange = 16;
  static const unsigned AddressWidth = 4;

//latency = 1
//input_reg = 1
//output_reg = 0
sc_core::sc_in <sc_lv<AddressWidth> > address0;
sc_core::sc_in <sc_logic> ce0;
sc_core::sc_out <sc_lv<DataWidth> > q0;
sc_core::sc_in<sc_logic> reset;
sc_core::sc_in<bool> clk;


sc_lv<DataWidth> ram[AddressRange];


   SC_CTOR(inference_conv2d_2_f2_1_4_2_ram) {
        ram[0] = "0b00111100000101011001000101010111";
        ram[1] = "0b10111101000001011001100000100101";
        ram[2] = "0b00111101001111001010110110110110";
        ram[3] = "0b10111101100010011101000101111101";
        ram[4] = "0b10111101010111101111100001001000";
        ram[5] = "0b00111101100000001010111000011110";
        ram[6] = "0b00111110001001000001100010010011";
        ram[7] = "0b10111101101101110110000001010100";
        ram[8] = "0b00111101000011000110000001111011";
        ram[9] = "0b10111011100010110100001101010101";
        ram[10] = "0b10111101110011110001101110101100";
        ram[11] = "0b00111101110001100010100101000101";
        ram[12] = "0b00111101111011101101010011100101";
        ram[13] = "0b10111101000100111101010001011110";
        ram[14] = "0b10111100011101111000110010010100";
        ram[15] = "0b00111100111111011001111111010011";


SC_METHOD(prc_write_0);
  sensitive<<clk.pos();
   }


void prc_write_0()
{
    if (ce0.read() == sc_dt::Log_1) 
    {
            if(address0.read().is_01() && address0.read().to_uint()<AddressRange)
              q0 = ram[address0.read().to_uint()];
            else
              q0 = sc_lv<DataWidth>();
    }
}


}; //endmodule


SC_MODULE(inference_conv2d_2_f2_1_4_2) {


static const unsigned DataWidth = 32;
static const unsigned AddressRange = 16;
static const unsigned AddressWidth = 4;

sc_core::sc_in <sc_lv<AddressWidth> > address0;
sc_core::sc_in<sc_logic> ce0;
sc_core::sc_out <sc_lv<DataWidth> > q0;
sc_core::sc_in<sc_logic> reset;
sc_core::sc_in<bool> clk;


inference_conv2d_2_f2_1_4_2_ram* meminst;


SC_CTOR(inference_conv2d_2_f2_1_4_2) {
meminst = new inference_conv2d_2_f2_1_4_2_ram("inference_conv2d_2_f2_1_4_2_ram");
meminst->address0(address0);
meminst->ce0(ce0);
meminst->q0(q0);

meminst->reset(reset);
meminst->clk(clk);
}
~inference_conv2d_2_f2_1_4_2() {
    delete meminst;
}


};//endmodule
#endif
