// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.4
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ==============================================================

#ifndef __inference_conv2d_2_f2_2_3_1_H__
#define __inference_conv2d_2_f2_2_3_1_H__


#include <systemc>
using namespace sc_core;
using namespace sc_dt;




#include <iostream>
#include <fstream>

struct inference_conv2d_2_f2_2_3_1_ram : public sc_core::sc_module {

  static const unsigned DataWidth = 32;
  static const unsigned AddressRange = 16;
  static const unsigned AddressWidth = 4;

//latency = 1
//input_reg = 1
//output_reg = 0
sc_core::sc_in <sc_lv<AddressWidth> > address0;
sc_core::sc_in <sc_logic> ce0;
sc_core::sc_out <sc_lv<DataWidth> > q0;
sc_core::sc_in<sc_logic> reset;
sc_core::sc_in<bool> clk;


sc_lv<DataWidth> ram[AddressRange];


   SC_CTOR(inference_conv2d_2_f2_2_3_1_ram) {
        ram[0] = "0b10111110000110111010100111010010";
        ram[1] = "0b10111100110101100010100010010110";
        ram[2] = "0b10111101111000010100110001100110";
        ram[3] = "0b10111110010010100111001100101110";
        ram[4] = "0b10111100111100110101011000000011";
        ram[5] = "0b10111100011110010001101010011110";
        ram[6] = "0b10111110001011111110000011001110";
        ram[7] = "0b10111101101101101111010011011001";
        ram[8] = "0b00111101000011011000011100100010";
        ram[9] = "0b10111110001010011101001010111111";
        ram[10] = "0b10111110100000101001011101011011";
        ram[11] = "0b10111101000000111100111100010010";
        ram[12] = "0b00111101100101000111101000100101";
        ram[13] = "0b10111101100111011011110001110100";
        ram[14] = "0b10111101111101000000011110001001";
        ram[15] = "0b00111110001111010001010010100001";


SC_METHOD(prc_write_0);
  sensitive<<clk.pos();
   }


void prc_write_0()
{
    if (ce0.read() == sc_dt::Log_1) 
    {
            if(address0.read().is_01() && address0.read().to_uint()<AddressRange)
              q0 = ram[address0.read().to_uint()];
            else
              q0 = sc_lv<DataWidth>();
    }
}


}; //endmodule


SC_MODULE(inference_conv2d_2_f2_2_3_1) {


static const unsigned DataWidth = 32;
static const unsigned AddressRange = 16;
static const unsigned AddressWidth = 4;

sc_core::sc_in <sc_lv<AddressWidth> > address0;
sc_core::sc_in<sc_logic> ce0;
sc_core::sc_out <sc_lv<DataWidth> > q0;
sc_core::sc_in<sc_logic> reset;
sc_core::sc_in<bool> clk;


inference_conv2d_2_f2_2_3_1_ram* meminst;


SC_CTOR(inference_conv2d_2_f2_2_3_1) {
meminst = new inference_conv2d_2_f2_2_3_1_ram("inference_conv2d_2_f2_2_3_1_ram");
meminst->address0(address0);
meminst->ce0(ce0);
meminst->q0(q0);

meminst->reset(reset);
meminst->clk(clk);
}
~inference_conv2d_2_f2_2_3_1() {
    delete meminst;
}


};//endmodule
#endif
