// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.4
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ==============================================================

#ifndef __inference_conv2d_2_f2_3_2_5_H__
#define __inference_conv2d_2_f2_3_2_5_H__


#include <systemc>
using namespace sc_core;
using namespace sc_dt;




#include <iostream>
#include <fstream>

struct inference_conv2d_2_f2_3_2_5_ram : public sc_core::sc_module {

  static const unsigned DataWidth = 32;
  static const unsigned AddressRange = 16;
  static const unsigned AddressWidth = 4;

//latency = 1
//input_reg = 1
//output_reg = 0
sc_core::sc_in <sc_lv<AddressWidth> > address0;
sc_core::sc_in <sc_logic> ce0;
sc_core::sc_out <sc_lv<DataWidth> > q0;
sc_core::sc_in<sc_logic> reset;
sc_core::sc_in<bool> clk;


sc_lv<DataWidth> ram[AddressRange];


   SC_CTOR(inference_conv2d_2_f2_3_2_5_ram) {
        ram[0] = "0b10111100000011110000111101100111";
        ram[1] = "0b00111101100000001000100111111110";
        ram[2] = "0b00111110000011000111001011100010";
        ram[3] = "0b00111110010011001010100000011010";
        ram[4] = "0b00111101110000101100111100101010";
        ram[5] = "0b10111101010010010110010001001000";
        ram[6] = "0b00111101101101100010011011110110";
        ram[7] = "0b10111101111010110000010110111000";
        ram[8] = "0b00111110001101000010010000011100";
        ram[9] = "0b10111100001100100100110101011010";
        ram[10] = "0b00111110010101101110000110011100";
        ram[11] = "0b10111101000001011100100010110010";
        ram[12] = "0b10111100101100011101100000011111";
        ram[13] = "0b00111110100000011111101001010101";
        ram[14] = "0b10111110001101101101001101110100";
        ram[15] = "0b10111100100010101010111110111100";


SC_METHOD(prc_write_0);
  sensitive<<clk.pos();
   }


void prc_write_0()
{
    if (ce0.read() == sc_dt::Log_1) 
    {
            if(address0.read().is_01() && address0.read().to_uint()<AddressRange)
              q0 = ram[address0.read().to_uint()];
            else
              q0 = sc_lv<DataWidth>();
    }
}


}; //endmodule


SC_MODULE(inference_conv2d_2_f2_3_2_5) {


static const unsigned DataWidth = 32;
static const unsigned AddressRange = 16;
static const unsigned AddressWidth = 4;

sc_core::sc_in <sc_lv<AddressWidth> > address0;
sc_core::sc_in<sc_logic> ce0;
sc_core::sc_out <sc_lv<DataWidth> > q0;
sc_core::sc_in<sc_logic> reset;
sc_core::sc_in<bool> clk;


inference_conv2d_2_f2_3_2_5_ram* meminst;


SC_CTOR(inference_conv2d_2_f2_3_2_5) {
meminst = new inference_conv2d_2_f2_3_2_5_ram("inference_conv2d_2_f2_3_2_5_ram");
meminst->address0(address0);
meminst->ce0(ce0);
meminst->q0(q0);

meminst->reset(reset);
meminst->clk(clk);
}
~inference_conv2d_2_f2_3_2_5() {
    delete meminst;
}


};//endmodule
#endif
