// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.4
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ==============================================================

#ifndef __inference_conv2d_2_f2_0_3_1_H__
#define __inference_conv2d_2_f2_0_3_1_H__


#include <systemc>
using namespace sc_core;
using namespace sc_dt;




#include <iostream>
#include <fstream>

struct inference_conv2d_2_f2_0_3_1_ram : public sc_core::sc_module {

  static const unsigned DataWidth = 32;
  static const unsigned AddressRange = 16;
  static const unsigned AddressWidth = 4;

//latency = 1
//input_reg = 1
//output_reg = 0
sc_core::sc_in <sc_lv<AddressWidth> > address0;
sc_core::sc_in <sc_logic> ce0;
sc_core::sc_out <sc_lv<DataWidth> > q0;
sc_core::sc_in<sc_logic> reset;
sc_core::sc_in<bool> clk;


sc_lv<DataWidth> ram[AddressRange];


   SC_CTOR(inference_conv2d_2_f2_0_3_1_ram) {
        ram[0] = "0b00111101110000000100011111000110";
        ram[1] = "0b00111110000100101111101010010100";
        ram[2] = "0b00111101001000110011011010011100";
        ram[3] = "0b00111101000011010100100010111110";
        ram[4] = "0b00111101000101100010101100110101";
        ram[5] = "0b00111110000011111011011111101001";
        ram[6] = "0b00111101111000000101111001011111";
        ram[7] = "0b00111100111000111000111010110000";
        ram[8] = "0b10111101101101110000001001111011";
        ram[9] = "0b10111101011011101100110011010010";
        ram[10] = "0b10111100100110001110111011100100";
        ram[11] = "0b10111101010101010010011101000100";
        ram[12] = "0b10111101001010111011011111000100";
        ram[13] = "0b10111101101000110111000100000011";
        ram[14] = "0b10111101010111011100110011001111";
        ram[15] = "0b00111101100100101011101000100100";


SC_METHOD(prc_write_0);
  sensitive<<clk.pos();
   }


void prc_write_0()
{
    if (ce0.read() == sc_dt::Log_1) 
    {
            if(address0.read().is_01() && address0.read().to_uint()<AddressRange)
              q0 = ram[address0.read().to_uint()];
            else
              q0 = sc_lv<DataWidth>();
    }
}


}; //endmodule


SC_MODULE(inference_conv2d_2_f2_0_3_1) {


static const unsigned DataWidth = 32;
static const unsigned AddressRange = 16;
static const unsigned AddressWidth = 4;

sc_core::sc_in <sc_lv<AddressWidth> > address0;
sc_core::sc_in<sc_logic> ce0;
sc_core::sc_out <sc_lv<DataWidth> > q0;
sc_core::sc_in<sc_logic> reset;
sc_core::sc_in<bool> clk;


inference_conv2d_2_f2_0_3_1_ram* meminst;


SC_CTOR(inference_conv2d_2_f2_0_3_1) {
meminst = new inference_conv2d_2_f2_0_3_1_ram("inference_conv2d_2_f2_0_3_1_ram");
meminst->address0(address0);
meminst->ce0(ce0);
meminst->q0(q0);

meminst->reset(reset);
meminst->clk(clk);
}
~inference_conv2d_2_f2_0_3_1() {
    delete meminst;
}


};//endmodule
#endif
