// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.4
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ==============================================================

#ifndef __inference_conv2d_2_f2_4_1_0_H__
#define __inference_conv2d_2_f2_4_1_0_H__


#include <systemc>
using namespace sc_core;
using namespace sc_dt;




#include <iostream>
#include <fstream>

struct inference_conv2d_2_f2_4_1_0_ram : public sc_core::sc_module {

  static const unsigned DataWidth = 32;
  static const unsigned AddressRange = 16;
  static const unsigned AddressWidth = 4;

//latency = 1
//input_reg = 1
//output_reg = 0
sc_core::sc_in <sc_lv<AddressWidth> > address0;
sc_core::sc_in <sc_logic> ce0;
sc_core::sc_out <sc_lv<DataWidth> > q0;
sc_core::sc_in<sc_logic> reset;
sc_core::sc_in<bool> clk;


sc_lv<DataWidth> ram[AddressRange];


   SC_CTOR(inference_conv2d_2_f2_4_1_0_ram) {
        ram[0] = "0b00111101011100010110110111100111";
        ram[1] = "0b10111100100111011011011001011111";
        ram[2] = "0b00111110010010010001111010101000";
        ram[3] = "0b00111101111100011111000101001010";
        ram[4] = "0b10111010110111000110110100101001";
        ram[5] = "0b10111110001001110110000000111001";
        ram[6] = "0b10111101111101000000101000101000";
        ram[7] = "0b10111101101111100101000010010000";
        ram[8] = "0b00111011000111000001000010010111";
        ram[9] = "0b00111110010001001011110101110111";
        ram[10] = "0b00111101110000010011000100100011";
        ram[11] = "0b10111101100110110011111111011101";
        ram[12] = "0b00111110010011010100000010101011";
        ram[13] = "0b00111110000011010000111011011100";
        ram[14] = "0b00111110000001010111101010111100";
        ram[15] = "0b10111100110110001010111100100011";


SC_METHOD(prc_write_0);
  sensitive<<clk.pos();
   }


void prc_write_0()
{
    if (ce0.read() == sc_dt::Log_1) 
    {
            if(address0.read().is_01() && address0.read().to_uint()<AddressRange)
              q0 = ram[address0.read().to_uint()];
            else
              q0 = sc_lv<DataWidth>();
    }
}


}; //endmodule


SC_MODULE(inference_conv2d_2_f2_4_1_0) {


static const unsigned DataWidth = 32;
static const unsigned AddressRange = 16;
static const unsigned AddressWidth = 4;

sc_core::sc_in <sc_lv<AddressWidth> > address0;
sc_core::sc_in<sc_logic> ce0;
sc_core::sc_out <sc_lv<DataWidth> > q0;
sc_core::sc_in<sc_logic> reset;
sc_core::sc_in<bool> clk;


inference_conv2d_2_f2_4_1_0_ram* meminst;


SC_CTOR(inference_conv2d_2_f2_4_1_0) {
meminst = new inference_conv2d_2_f2_4_1_0_ram("inference_conv2d_2_f2_4_1_0_ram");
meminst->address0(address0);
meminst->ce0(ce0);
meminst->q0(q0);

meminst->reset(reset);
meminst->clk(clk);
}
~inference_conv2d_2_f2_4_1_0() {
    delete meminst;
}


};//endmodule
#endif
