// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.4
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ==============================================================

#ifndef __inference_conv2d_2_f2_0_4_0_H__
#define __inference_conv2d_2_f2_0_4_0_H__


#include <systemc>
using namespace sc_core;
using namespace sc_dt;




#include <iostream>
#include <fstream>

struct inference_conv2d_2_f2_0_4_0_ram : public sc_core::sc_module {

  static const unsigned DataWidth = 32;
  static const unsigned AddressRange = 16;
  static const unsigned AddressWidth = 4;

//latency = 1
//input_reg = 1
//output_reg = 0
sc_core::sc_in <sc_lv<AddressWidth> > address0;
sc_core::sc_in <sc_logic> ce0;
sc_core::sc_out <sc_lv<DataWidth> > q0;
sc_core::sc_in<sc_logic> reset;
sc_core::sc_in<bool> clk;


sc_lv<DataWidth> ram[AddressRange];


   SC_CTOR(inference_conv2d_2_f2_0_4_0_ram) {
        ram[0] = "0b00111110011001001010110010110000";
        ram[1] = "0b00111110100000001111111010101100";
        ram[2] = "0b00111100000100010000111111101000";
        ram[3] = "0b00111110100100101110110000000111";
        ram[4] = "0b10111101110000100011110010010011";
        ram[5] = "0b00111110000101100101000011100111";
        ram[6] = "0b00111110000000001010100011010010";
        ram[7] = "0b00111101111101110011001010011100";
        ram[8] = "0b10111110000110001110111110111011";
        ram[9] = "0b00111110000011101011000111000100";
        ram[10] = "0b00111110001100001001000001110001";
        ram[11] = "0b10111110100100111000011101111011";
        ram[12] = "0b00111100011001010001100111001011";
        ram[13] = "0b00111100111111110011001000001111";
        ram[14] = "0b10111101011001110101000111101001";
        ram[15] = "0b10111101010001111111001011000011";


SC_METHOD(prc_write_0);
  sensitive<<clk.pos();
   }


void prc_write_0()
{
    if (ce0.read() == sc_dt::Log_1) 
    {
            if(address0.read().is_01() && address0.read().to_uint()<AddressRange)
              q0 = ram[address0.read().to_uint()];
            else
              q0 = sc_lv<DataWidth>();
    }
}


}; //endmodule


SC_MODULE(inference_conv2d_2_f2_0_4_0) {


static const unsigned DataWidth = 32;
static const unsigned AddressRange = 16;
static const unsigned AddressWidth = 4;

sc_core::sc_in <sc_lv<AddressWidth> > address0;
sc_core::sc_in<sc_logic> ce0;
sc_core::sc_out <sc_lv<DataWidth> > q0;
sc_core::sc_in<sc_logic> reset;
sc_core::sc_in<bool> clk;


inference_conv2d_2_f2_0_4_0_ram* meminst;


SC_CTOR(inference_conv2d_2_f2_0_4_0) {
meminst = new inference_conv2d_2_f2_0_4_0_ram("inference_conv2d_2_f2_0_4_0_ram");
meminst->address0(address0);
meminst->ce0(ce0);
meminst->q0(q0);

meminst->reset(reset);
meminst->clk(clk);
}
~inference_conv2d_2_f2_0_4_0() {
    delete meminst;
}


};//endmodule
#endif
