// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.4
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ==============================================================

#ifndef __inference_conv2d_2_f2_2_1_0_H__
#define __inference_conv2d_2_f2_2_1_0_H__


#include <systemc>
using namespace sc_core;
using namespace sc_dt;




#include <iostream>
#include <fstream>

struct inference_conv2d_2_f2_2_1_0_ram : public sc_core::sc_module {

  static const unsigned DataWidth = 32;
  static const unsigned AddressRange = 16;
  static const unsigned AddressWidth = 4;

//latency = 1
//input_reg = 1
//output_reg = 0
sc_core::sc_in <sc_lv<AddressWidth> > address0;
sc_core::sc_in <sc_logic> ce0;
sc_core::sc_out <sc_lv<DataWidth> > q0;
sc_core::sc_in<sc_logic> reset;
sc_core::sc_in<bool> clk;


sc_lv<DataWidth> ram[AddressRange];


   SC_CTOR(inference_conv2d_2_f2_2_1_0_ram) {
        ram[0] = "0b00111101101110001101010101001110";
        ram[1] = "0b00111101010111110010111001001001";
        ram[2] = "0b00111011110110001110101010101000";
        ram[3] = "0b00111110000100111111010111111001";
        ram[4] = "0b00111110010001001100100001111010";
        ram[5] = "0b00111101100111010111011101110101";
        ram[6] = "0b10111110000111000110001100101000";
        ram[7] = "0b00111101001111110000011101100010";
        ram[8] = "0b10111110000110000110100010111010";
        ram[9] = "0b00111101001001010011111111011011";
        ram[10] = "0b00111101101001010001000110011101";
        ram[11] = "0b00111101010101111100100110000000";
        ram[12] = "0b10111101110010110101101010100111";
        ram[13] = "0b10111101010011001011101000111101";
        ram[14] = "0b10111101001011000011000100010110";
        ram[15] = "0b10111101100101010010110010111000";


SC_METHOD(prc_write_0);
  sensitive<<clk.pos();
   }


void prc_write_0()
{
    if (ce0.read() == sc_dt::Log_1) 
    {
            if(address0.read().is_01() && address0.read().to_uint()<AddressRange)
              q0 = ram[address0.read().to_uint()];
            else
              q0 = sc_lv<DataWidth>();
    }
}


}; //endmodule


SC_MODULE(inference_conv2d_2_f2_2_1_0) {


static const unsigned DataWidth = 32;
static const unsigned AddressRange = 16;
static const unsigned AddressWidth = 4;

sc_core::sc_in <sc_lv<AddressWidth> > address0;
sc_core::sc_in<sc_logic> ce0;
sc_core::sc_out <sc_lv<DataWidth> > q0;
sc_core::sc_in<sc_logic> reset;
sc_core::sc_in<bool> clk;


inference_conv2d_2_f2_2_1_0_ram* meminst;


SC_CTOR(inference_conv2d_2_f2_2_1_0) {
meminst = new inference_conv2d_2_f2_2_1_0_ram("inference_conv2d_2_f2_2_1_0_ram");
meminst->address0(address0);
meminst->ce0(ce0);
meminst->q0(q0);

meminst->reset(reset);
meminst->clk(clk);
}
~inference_conv2d_2_f2_2_1_0() {
    delete meminst;
}


};//endmodule
#endif
