// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.4
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ==============================================================

#ifndef __inference_conv2d_2_f2_1_4_4_H__
#define __inference_conv2d_2_f2_1_4_4_H__


#include <systemc>
using namespace sc_core;
using namespace sc_dt;




#include <iostream>
#include <fstream>

struct inference_conv2d_2_f2_1_4_4_ram : public sc_core::sc_module {

  static const unsigned DataWidth = 32;
  static const unsigned AddressRange = 16;
  static const unsigned AddressWidth = 4;

//latency = 1
//input_reg = 1
//output_reg = 0
sc_core::sc_in <sc_lv<AddressWidth> > address0;
sc_core::sc_in <sc_logic> ce0;
sc_core::sc_out <sc_lv<DataWidth> > q0;
sc_core::sc_in<sc_logic> reset;
sc_core::sc_in<bool> clk;


sc_lv<DataWidth> ram[AddressRange];


   SC_CTOR(inference_conv2d_2_f2_1_4_4_ram) {
        ram[0] = "0b10111110000001000010001010001010";
        ram[1] = "0b10111110010001000000110010000100";
        ram[2] = "0b00111101110000001100010001001011";
        ram[3] = "0b00111101100001111010111110100111";
        ram[4] = "0b10111101100001100000110010001001";
        ram[5] = "0b10111101111010000111110100101100";
        ram[6] = "0b10111011001000011111011000001010";
        ram[7] = "0b00111100101010101011000010101110";
        ram[8] = "0b00111110000111001100101000101110";
        ram[9] = "0b00111101001110100010000100101110";
        ram[10] = "0b10111010010000000110100100011010";
        ram[11] = "0b00111100110001011011101011000000";
        ram[12] = "0b10111110001011101000110000000101";
        ram[13] = "0b00111110000000111001010111000100";
        ram[14] = "0b00111110011100011100110010010110";
        ram[15] = "0b00111101110001110001101101001000";


SC_METHOD(prc_write_0);
  sensitive<<clk.pos();
   }


void prc_write_0()
{
    if (ce0.read() == sc_dt::Log_1) 
    {
            if(address0.read().is_01() && address0.read().to_uint()<AddressRange)
              q0 = ram[address0.read().to_uint()];
            else
              q0 = sc_lv<DataWidth>();
    }
}


}; //endmodule


SC_MODULE(inference_conv2d_2_f2_1_4_4) {


static const unsigned DataWidth = 32;
static const unsigned AddressRange = 16;
static const unsigned AddressWidth = 4;

sc_core::sc_in <sc_lv<AddressWidth> > address0;
sc_core::sc_in<sc_logic> ce0;
sc_core::sc_out <sc_lv<DataWidth> > q0;
sc_core::sc_in<sc_logic> reset;
sc_core::sc_in<bool> clk;


inference_conv2d_2_f2_1_4_4_ram* meminst;


SC_CTOR(inference_conv2d_2_f2_1_4_4) {
meminst = new inference_conv2d_2_f2_1_4_4_ram("inference_conv2d_2_f2_1_4_4_ram");
meminst->address0(address0);
meminst->ce0(ce0);
meminst->q0(q0);

meminst->reset(reset);
meminst->clk(clk);
}
~inference_conv2d_2_f2_1_4_4() {
    delete meminst;
}


};//endmodule
#endif
