// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.4
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ==============================================================

#ifndef __inference_conv2d_2_b2_H__
#define __inference_conv2d_2_b2_H__


#include <systemc>
using namespace sc_core;
using namespace sc_dt;




#include <iostream>
#include <fstream>

struct inference_conv2d_2_b2_ram : public sc_core::sc_module {

  static const unsigned DataWidth = 32;
  static const unsigned AddressRange = 16;
  static const unsigned AddressWidth = 4;

//latency = 1
//input_reg = 1
//output_reg = 0
sc_core::sc_in <sc_lv<AddressWidth> > address0;
sc_core::sc_in <sc_logic> ce0;
sc_core::sc_out <sc_lv<DataWidth> > q0;
sc_core::sc_in<sc_logic> reset;
sc_core::sc_in<bool> clk;


sc_lv<DataWidth> ram[AddressRange];


   SC_CTOR(inference_conv2d_2_b2_ram) {
        ram[0] = "0b00111110001000111011001001010111";
        ram[1] = "0b00111101111110010111101110110111";
        ram[2] = "0b00111101110100101111111111010010";
        ram[3] = "0b00111101110001111011010011110011";
        ram[4] = "0b00111101101001000111000100101110";
        ram[5] = "0b00111101100110100100101011001111";
        ram[6] = "0b00111101011011110101110111010110";
        ram[7] = "0b00111101100111011111011110001010";
        ram[8] = "0b00111110000110101100010101111110";
        ram[9] = "0b00111101111110110011001100010010";
        ram[10] = "0b00111101110010011110001101011110";
        ram[11] = "0b00111101110101000100011011111010";
        ram[12] = "0b00111101010011000001010100010111";
        ram[13] = "0b00111101101101000111111101111110";
        ram[14] = "0b00111101101101000000111110000001";
        ram[15] = "0b00111101101010110010101101001111";


SC_METHOD(prc_write_0);
  sensitive<<clk.pos();
   }


void prc_write_0()
{
    if (ce0.read() == sc_dt::Log_1) 
    {
            if(address0.read().is_01() && address0.read().to_uint()<AddressRange)
              q0 = ram[address0.read().to_uint()];
            else
              q0 = sc_lv<DataWidth>();
    }
}


}; //endmodule


SC_MODULE(inference_conv2d_2_b2) {


static const unsigned DataWidth = 32;
static const unsigned AddressRange = 16;
static const unsigned AddressWidth = 4;

sc_core::sc_in <sc_lv<AddressWidth> > address0;
sc_core::sc_in<sc_logic> ce0;
sc_core::sc_out <sc_lv<DataWidth> > q0;
sc_core::sc_in<sc_logic> reset;
sc_core::sc_in<bool> clk;


inference_conv2d_2_b2_ram* meminst;


SC_CTOR(inference_conv2d_2_b2) {
meminst = new inference_conv2d_2_b2_ram("inference_conv2d_2_b2_ram");
meminst->address0(address0);
meminst->ce0(ce0);
meminst->q0(q0);

meminst->reset(reset);
meminst->clk(clk);
}
~inference_conv2d_2_b2() {
    delete meminst;
}


};//endmodule
#endif
