// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.4
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ===========================================================

#include "inference_sm.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic inference_sm::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic inference_sm::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<6> inference_sm::ap_ST_st1_fsm_0 = "1";
const sc_lv<6> inference_sm::ap_ST_st2_fsm_1 = "10";
const sc_lv<6> inference_sm::ap_ST_st3_fsm_2 = "100";
const sc_lv<6> inference_sm::ap_ST_st4_fsm_3 = "1000";
const sc_lv<6> inference_sm::ap_ST_st5_fsm_4 = "10000";
const sc_lv<6> inference_sm::ap_ST_st6_fsm_5 = "100000";
const sc_lv<32> inference_sm::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<1> inference_sm::ap_const_lv1_1 = "1";
const sc_lv<32> inference_sm::ap_const_lv32_1 = "1";
const sc_lv<32> inference_sm::ap_const_lv32_2 = "10";
const sc_lv<32> inference_sm::ap_const_lv32_3 = "11";
const sc_lv<32> inference_sm::ap_const_lv32_4 = "100";
const sc_lv<32> inference_sm::ap_const_lv32_5 = "101";

inference_sm::inference_sm(sc_module_name name) : sc_module(name), mVcdFile(0) {
    T_0_0_U = new inference_sm_T_0_0("T_0_0_U");
    T_0_0_U->clk(ap_clk);
    T_0_0_U->reset(ap_rst);
    T_0_0_U->address0(T_0_0_address0);
    T_0_0_U->ce0(T_0_0_ce0);
    T_0_0_U->we0(T_0_0_we0);
    T_0_0_U->d0(T_0_0_d0);
    T_0_0_U->q0(T_0_0_q0);
    T_1_0_U = new inference_sm_T_0_0("T_1_0_U");
    T_1_0_U->clk(ap_clk);
    T_1_0_U->reset(ap_rst);
    T_1_0_U->address0(T_1_0_address0);
    T_1_0_U->ce0(T_1_0_ce0);
    T_1_0_U->we0(T_1_0_we0);
    T_1_0_U->d0(T_1_0_d0);
    T_1_0_U->q0(T_1_0_q0);
    T_2_0_U = new inference_sm_T_2_0("T_2_0_U");
    T_2_0_U->clk(ap_clk);
    T_2_0_U->reset(ap_rst);
    T_2_0_U->address0(T_2_0_address0);
    T_2_0_U->ce0(T_2_0_ce0);
    T_2_0_U->we0(T_2_0_we0);
    T_2_0_U->d0(T_2_0_d0);
    T_2_0_U->q0(T_2_0_q0);
    T_3_0_U = new inference_sm_T_2_0("T_3_0_U");
    T_3_0_U->clk(ap_clk);
    T_3_0_U->reset(ap_rst);
    T_3_0_U->address0(T_3_0_address0);
    T_3_0_U->ce0(T_3_0_ce0);
    T_3_0_U->we0(T_3_0_we0);
    T_3_0_U->d0(T_3_0_d0);
    T_3_0_U->q0(T_3_0_q0);
    S_0_0_U = new inference_sm_T_0_0("S_0_0_U");
    S_0_0_U->clk(ap_clk);
    S_0_0_U->reset(ap_rst);
    S_0_0_U->address0(S_0_0_address0);
    S_0_0_U->ce0(S_0_0_ce0);
    S_0_0_U->we0(S_0_0_we0);
    S_0_0_U->d0(S_0_0_d0);
    S_0_0_U->q0(S_0_0_q0);
    S_1_0_U = new inference_sm_T_0_0("S_1_0_U");
    S_1_0_U->clk(ap_clk);
    S_1_0_U->reset(ap_rst);
    S_1_0_U->address0(S_1_0_address0);
    S_1_0_U->ce0(S_1_0_ce0);
    S_1_0_U->we0(S_1_0_we0);
    S_1_0_U->d0(S_1_0_d0);
    S_1_0_U->q0(S_1_0_q0);
    S_2_0_U = new inference_sm_T_2_0("S_2_0_U");
    S_2_0_U->clk(ap_clk);
    S_2_0_U->reset(ap_rst);
    S_2_0_U->address0(S_2_0_address0);
    S_2_0_U->ce0(S_2_0_ce0);
    S_2_0_U->we0(S_2_0_we0);
    S_2_0_U->d0(S_2_0_d0);
    S_2_0_U->q0(S_2_0_q0);
    S_3_0_U = new inference_sm_T_2_0("S_3_0_U");
    S_3_0_U->clk(ap_clk);
    S_3_0_U->reset(ap_rst);
    S_3_0_U->address0(S_3_0_address0);
    S_3_0_U->ce0(S_3_0_ce0);
    S_3_0_U->we0(S_3_0_we0);
    S_3_0_U->d0(S_3_0_d0);
    S_3_0_U->q0(S_3_0_q0);
    grp_inference_mult_1_84_84_10_s_fu_228 = new inference_mult_1_84_84_10_s("grp_inference_mult_1_84_84_10_s_fu_228");
    grp_inference_mult_1_84_84_10_s_fu_228->ap_clk(ap_clk);
    grp_inference_mult_1_84_84_10_s_fu_228->ap_rst(ap_rst);
    grp_inference_mult_1_84_84_10_s_fu_228->ap_start(grp_inference_mult_1_84_84_10_s_fu_228_ap_start);
    grp_inference_mult_1_84_84_10_s_fu_228->ap_done(grp_inference_mult_1_84_84_10_s_fu_228_ap_done);
    grp_inference_mult_1_84_84_10_s_fu_228->ap_idle(grp_inference_mult_1_84_84_10_s_fu_228_ap_idle);
    grp_inference_mult_1_84_84_10_s_fu_228->ap_ready(grp_inference_mult_1_84_84_10_s_fu_228_ap_ready);
    grp_inference_mult_1_84_84_10_s_fu_228->A_0_0_address0(grp_inference_mult_1_84_84_10_s_fu_228_A_0_0_address0);
    grp_inference_mult_1_84_84_10_s_fu_228->A_0_0_ce0(grp_inference_mult_1_84_84_10_s_fu_228_A_0_0_ce0);
    grp_inference_mult_1_84_84_10_s_fu_228->A_0_0_q0(grp_inference_mult_1_84_84_10_s_fu_228_A_0_0_q0);
    grp_inference_mult_1_84_84_10_s_fu_228->A_0_0_address1(grp_inference_mult_1_84_84_10_s_fu_228_A_0_0_address1);
    grp_inference_mult_1_84_84_10_s_fu_228->A_0_0_ce1(grp_inference_mult_1_84_84_10_s_fu_228_A_0_0_ce1);
    grp_inference_mult_1_84_84_10_s_fu_228->A_0_0_q1(grp_inference_mult_1_84_84_10_s_fu_228_A_0_0_q1);
    grp_inference_mult_1_84_84_10_s_fu_228->A_1_0_address0(grp_inference_mult_1_84_84_10_s_fu_228_A_1_0_address0);
    grp_inference_mult_1_84_84_10_s_fu_228->A_1_0_ce0(grp_inference_mult_1_84_84_10_s_fu_228_A_1_0_ce0);
    grp_inference_mult_1_84_84_10_s_fu_228->A_1_0_q0(grp_inference_mult_1_84_84_10_s_fu_228_A_1_0_q0);
    grp_inference_mult_1_84_84_10_s_fu_228->A_1_0_address1(grp_inference_mult_1_84_84_10_s_fu_228_A_1_0_address1);
    grp_inference_mult_1_84_84_10_s_fu_228->A_1_0_ce1(grp_inference_mult_1_84_84_10_s_fu_228_A_1_0_ce1);
    grp_inference_mult_1_84_84_10_s_fu_228->A_1_0_q1(grp_inference_mult_1_84_84_10_s_fu_228_A_1_0_q1);
    grp_inference_mult_1_84_84_10_s_fu_228->A_2_0_address0(grp_inference_mult_1_84_84_10_s_fu_228_A_2_0_address0);
    grp_inference_mult_1_84_84_10_s_fu_228->A_2_0_ce0(grp_inference_mult_1_84_84_10_s_fu_228_A_2_0_ce0);
    grp_inference_mult_1_84_84_10_s_fu_228->A_2_0_q0(grp_inference_mult_1_84_84_10_s_fu_228_A_2_0_q0);
    grp_inference_mult_1_84_84_10_s_fu_228->A_2_0_address1(grp_inference_mult_1_84_84_10_s_fu_228_A_2_0_address1);
    grp_inference_mult_1_84_84_10_s_fu_228->A_2_0_ce1(grp_inference_mult_1_84_84_10_s_fu_228_A_2_0_ce1);
    grp_inference_mult_1_84_84_10_s_fu_228->A_2_0_q1(grp_inference_mult_1_84_84_10_s_fu_228_A_2_0_q1);
    grp_inference_mult_1_84_84_10_s_fu_228->A_3_0_address0(grp_inference_mult_1_84_84_10_s_fu_228_A_3_0_address0);
    grp_inference_mult_1_84_84_10_s_fu_228->A_3_0_ce0(grp_inference_mult_1_84_84_10_s_fu_228_A_3_0_ce0);
    grp_inference_mult_1_84_84_10_s_fu_228->A_3_0_q0(grp_inference_mult_1_84_84_10_s_fu_228_A_3_0_q0);
    grp_inference_mult_1_84_84_10_s_fu_228->A_3_0_address1(grp_inference_mult_1_84_84_10_s_fu_228_A_3_0_address1);
    grp_inference_mult_1_84_84_10_s_fu_228->A_3_0_ce1(grp_inference_mult_1_84_84_10_s_fu_228_A_3_0_ce1);
    grp_inference_mult_1_84_84_10_s_fu_228->A_3_0_q1(grp_inference_mult_1_84_84_10_s_fu_228_A_3_0_q1);
    grp_inference_mult_1_84_84_10_s_fu_228->C_0_0_address0(grp_inference_mult_1_84_84_10_s_fu_228_C_0_0_address0);
    grp_inference_mult_1_84_84_10_s_fu_228->C_0_0_ce0(grp_inference_mult_1_84_84_10_s_fu_228_C_0_0_ce0);
    grp_inference_mult_1_84_84_10_s_fu_228->C_0_0_we0(grp_inference_mult_1_84_84_10_s_fu_228_C_0_0_we0);
    grp_inference_mult_1_84_84_10_s_fu_228->C_0_0_d0(grp_inference_mult_1_84_84_10_s_fu_228_C_0_0_d0);
    grp_inference_mult_1_84_84_10_s_fu_228->C_1_0_address0(grp_inference_mult_1_84_84_10_s_fu_228_C_1_0_address0);
    grp_inference_mult_1_84_84_10_s_fu_228->C_1_0_ce0(grp_inference_mult_1_84_84_10_s_fu_228_C_1_0_ce0);
    grp_inference_mult_1_84_84_10_s_fu_228->C_1_0_we0(grp_inference_mult_1_84_84_10_s_fu_228_C_1_0_we0);
    grp_inference_mult_1_84_84_10_s_fu_228->C_1_0_d0(grp_inference_mult_1_84_84_10_s_fu_228_C_1_0_d0);
    grp_inference_mult_1_84_84_10_s_fu_228->C_2_0_address0(grp_inference_mult_1_84_84_10_s_fu_228_C_2_0_address0);
    grp_inference_mult_1_84_84_10_s_fu_228->C_2_0_ce0(grp_inference_mult_1_84_84_10_s_fu_228_C_2_0_ce0);
    grp_inference_mult_1_84_84_10_s_fu_228->C_2_0_we0(grp_inference_mult_1_84_84_10_s_fu_228_C_2_0_we0);
    grp_inference_mult_1_84_84_10_s_fu_228->C_2_0_d0(grp_inference_mult_1_84_84_10_s_fu_228_C_2_0_d0);
    grp_inference_mult_1_84_84_10_s_fu_228->C_3_0_address0(grp_inference_mult_1_84_84_10_s_fu_228_C_3_0_address0);
    grp_inference_mult_1_84_84_10_s_fu_228->C_3_0_ce0(grp_inference_mult_1_84_84_10_s_fu_228_C_3_0_ce0);
    grp_inference_mult_1_84_84_10_s_fu_228->C_3_0_we0(grp_inference_mult_1_84_84_10_s_fu_228_C_3_0_we0);
    grp_inference_mult_1_84_84_10_s_fu_228->C_3_0_d0(grp_inference_mult_1_84_84_10_s_fu_228_C_3_0_d0);
    grp_inference_add_1_10_s_fu_416 = new inference_add_1_10_s("grp_inference_add_1_10_s_fu_416");
    grp_inference_add_1_10_s_fu_416->ap_clk(ap_clk);
    grp_inference_add_1_10_s_fu_416->ap_rst(ap_rst);
    grp_inference_add_1_10_s_fu_416->ap_start(grp_inference_add_1_10_s_fu_416_ap_start);
    grp_inference_add_1_10_s_fu_416->ap_done(grp_inference_add_1_10_s_fu_416_ap_done);
    grp_inference_add_1_10_s_fu_416->ap_idle(grp_inference_add_1_10_s_fu_416_ap_idle);
    grp_inference_add_1_10_s_fu_416->ap_ready(grp_inference_add_1_10_s_fu_416_ap_ready);
    grp_inference_add_1_10_s_fu_416->A_0_0_address0(grp_inference_add_1_10_s_fu_416_A_0_0_address0);
    grp_inference_add_1_10_s_fu_416->A_0_0_ce0(grp_inference_add_1_10_s_fu_416_A_0_0_ce0);
    grp_inference_add_1_10_s_fu_416->A_0_0_q0(grp_inference_add_1_10_s_fu_416_A_0_0_q0);
    grp_inference_add_1_10_s_fu_416->A_1_0_address0(grp_inference_add_1_10_s_fu_416_A_1_0_address0);
    grp_inference_add_1_10_s_fu_416->A_1_0_ce0(grp_inference_add_1_10_s_fu_416_A_1_0_ce0);
    grp_inference_add_1_10_s_fu_416->A_1_0_q0(grp_inference_add_1_10_s_fu_416_A_1_0_q0);
    grp_inference_add_1_10_s_fu_416->A_2_0_address0(grp_inference_add_1_10_s_fu_416_A_2_0_address0);
    grp_inference_add_1_10_s_fu_416->A_2_0_ce0(grp_inference_add_1_10_s_fu_416_A_2_0_ce0);
    grp_inference_add_1_10_s_fu_416->A_2_0_q0(grp_inference_add_1_10_s_fu_416_A_2_0_q0);
    grp_inference_add_1_10_s_fu_416->A_3_0_address0(grp_inference_add_1_10_s_fu_416_A_3_0_address0);
    grp_inference_add_1_10_s_fu_416->A_3_0_ce0(grp_inference_add_1_10_s_fu_416_A_3_0_ce0);
    grp_inference_add_1_10_s_fu_416->A_3_0_q0(grp_inference_add_1_10_s_fu_416_A_3_0_q0);
    grp_inference_add_1_10_s_fu_416->C_0_0_address0(grp_inference_add_1_10_s_fu_416_C_0_0_address0);
    grp_inference_add_1_10_s_fu_416->C_0_0_ce0(grp_inference_add_1_10_s_fu_416_C_0_0_ce0);
    grp_inference_add_1_10_s_fu_416->C_0_0_we0(grp_inference_add_1_10_s_fu_416_C_0_0_we0);
    grp_inference_add_1_10_s_fu_416->C_0_0_d0(grp_inference_add_1_10_s_fu_416_C_0_0_d0);
    grp_inference_add_1_10_s_fu_416->C_1_0_address0(grp_inference_add_1_10_s_fu_416_C_1_0_address0);
    grp_inference_add_1_10_s_fu_416->C_1_0_ce0(grp_inference_add_1_10_s_fu_416_C_1_0_ce0);
    grp_inference_add_1_10_s_fu_416->C_1_0_we0(grp_inference_add_1_10_s_fu_416_C_1_0_we0);
    grp_inference_add_1_10_s_fu_416->C_1_0_d0(grp_inference_add_1_10_s_fu_416_C_1_0_d0);
    grp_inference_add_1_10_s_fu_416->C_2_0_address0(grp_inference_add_1_10_s_fu_416_C_2_0_address0);
    grp_inference_add_1_10_s_fu_416->C_2_0_ce0(grp_inference_add_1_10_s_fu_416_C_2_0_ce0);
    grp_inference_add_1_10_s_fu_416->C_2_0_we0(grp_inference_add_1_10_s_fu_416_C_2_0_we0);
    grp_inference_add_1_10_s_fu_416->C_2_0_d0(grp_inference_add_1_10_s_fu_416_C_2_0_d0);
    grp_inference_add_1_10_s_fu_416->C_3_0_address0(grp_inference_add_1_10_s_fu_416_C_3_0_address0);
    grp_inference_add_1_10_s_fu_416->C_3_0_ce0(grp_inference_add_1_10_s_fu_416_C_3_0_ce0);
    grp_inference_add_1_10_s_fu_416->C_3_0_we0(grp_inference_add_1_10_s_fu_416_C_3_0_we0);
    grp_inference_add_1_10_s_fu_416->C_3_0_d0(grp_inference_add_1_10_s_fu_416_C_3_0_d0);
    grp_inference_softmax_1_10_s_fu_430 = new inference_softmax_1_10_s("grp_inference_softmax_1_10_s_fu_430");
    grp_inference_softmax_1_10_s_fu_430->ap_clk(ap_clk);
    grp_inference_softmax_1_10_s_fu_430->ap_rst(ap_rst);
    grp_inference_softmax_1_10_s_fu_430->ap_start(grp_inference_softmax_1_10_s_fu_430_ap_start);
    grp_inference_softmax_1_10_s_fu_430->ap_done(grp_inference_softmax_1_10_s_fu_430_ap_done);
    grp_inference_softmax_1_10_s_fu_430->ap_idle(grp_inference_softmax_1_10_s_fu_430_ap_idle);
    grp_inference_softmax_1_10_s_fu_430->ap_ready(grp_inference_softmax_1_10_s_fu_430_ap_ready);
    grp_inference_softmax_1_10_s_fu_430->A_0_0_address0(grp_inference_softmax_1_10_s_fu_430_A_0_0_address0);
    grp_inference_softmax_1_10_s_fu_430->A_0_0_ce0(grp_inference_softmax_1_10_s_fu_430_A_0_0_ce0);
    grp_inference_softmax_1_10_s_fu_430->A_0_0_q0(grp_inference_softmax_1_10_s_fu_430_A_0_0_q0);
    grp_inference_softmax_1_10_s_fu_430->A_1_0_address0(grp_inference_softmax_1_10_s_fu_430_A_1_0_address0);
    grp_inference_softmax_1_10_s_fu_430->A_1_0_ce0(grp_inference_softmax_1_10_s_fu_430_A_1_0_ce0);
    grp_inference_softmax_1_10_s_fu_430->A_1_0_q0(grp_inference_softmax_1_10_s_fu_430_A_1_0_q0);
    grp_inference_softmax_1_10_s_fu_430->A_2_0_address0(grp_inference_softmax_1_10_s_fu_430_A_2_0_address0);
    grp_inference_softmax_1_10_s_fu_430->A_2_0_ce0(grp_inference_softmax_1_10_s_fu_430_A_2_0_ce0);
    grp_inference_softmax_1_10_s_fu_430->A_2_0_q0(grp_inference_softmax_1_10_s_fu_430_A_2_0_q0);
    grp_inference_softmax_1_10_s_fu_430->A_3_0_address0(grp_inference_softmax_1_10_s_fu_430_A_3_0_address0);
    grp_inference_softmax_1_10_s_fu_430->A_3_0_ce0(grp_inference_softmax_1_10_s_fu_430_A_3_0_ce0);
    grp_inference_softmax_1_10_s_fu_430->A_3_0_q0(grp_inference_softmax_1_10_s_fu_430_A_3_0_q0);
    grp_inference_softmax_1_10_s_fu_430->argmax_TDATA(grp_inference_softmax_1_10_s_fu_430_argmax_TDATA);
    grp_inference_softmax_1_10_s_fu_430->argmax_TVALID(grp_inference_softmax_1_10_s_fu_430_argmax_TVALID);
    grp_inference_softmax_1_10_s_fu_430->argmax_TREADY(grp_inference_softmax_1_10_s_fu_430_argmax_TREADY);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_S_0_0_address0);
    sensitive << ( grp_inference_add_1_10_s_fu_416_C_0_0_address0 );
    sensitive << ( grp_inference_softmax_1_10_s_fu_430_A_0_0_address0 );
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );
    sensitive << ( ap_sig_cseq_ST_st6_fsm_5 );

    SC_METHOD(thread_S_0_0_ce0);
    sensitive << ( grp_inference_add_1_10_s_fu_416_C_0_0_ce0 );
    sensitive << ( grp_inference_softmax_1_10_s_fu_430_A_0_0_ce0 );
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );
    sensitive << ( ap_sig_cseq_ST_st6_fsm_5 );

    SC_METHOD(thread_S_0_0_d0);
    sensitive << ( grp_inference_add_1_10_s_fu_416_C_0_0_d0 );
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );

    SC_METHOD(thread_S_0_0_we0);
    sensitive << ( grp_inference_add_1_10_s_fu_416_C_0_0_we0 );
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );

    SC_METHOD(thread_S_1_0_address0);
    sensitive << ( grp_inference_add_1_10_s_fu_416_C_1_0_address0 );
    sensitive << ( grp_inference_softmax_1_10_s_fu_430_A_1_0_address0 );
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );
    sensitive << ( ap_sig_cseq_ST_st6_fsm_5 );

    SC_METHOD(thread_S_1_0_ce0);
    sensitive << ( grp_inference_add_1_10_s_fu_416_C_1_0_ce0 );
    sensitive << ( grp_inference_softmax_1_10_s_fu_430_A_1_0_ce0 );
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );
    sensitive << ( ap_sig_cseq_ST_st6_fsm_5 );

    SC_METHOD(thread_S_1_0_d0);
    sensitive << ( grp_inference_add_1_10_s_fu_416_C_1_0_d0 );
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );

    SC_METHOD(thread_S_1_0_we0);
    sensitive << ( grp_inference_add_1_10_s_fu_416_C_1_0_we0 );
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );

    SC_METHOD(thread_S_2_0_address0);
    sensitive << ( grp_inference_add_1_10_s_fu_416_C_2_0_address0 );
    sensitive << ( grp_inference_softmax_1_10_s_fu_430_A_2_0_address0 );
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );
    sensitive << ( ap_sig_cseq_ST_st6_fsm_5 );

    SC_METHOD(thread_S_2_0_ce0);
    sensitive << ( grp_inference_add_1_10_s_fu_416_C_2_0_ce0 );
    sensitive << ( grp_inference_softmax_1_10_s_fu_430_A_2_0_ce0 );
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );
    sensitive << ( ap_sig_cseq_ST_st6_fsm_5 );

    SC_METHOD(thread_S_2_0_d0);
    sensitive << ( grp_inference_add_1_10_s_fu_416_C_2_0_d0 );
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );

    SC_METHOD(thread_S_2_0_we0);
    sensitive << ( grp_inference_add_1_10_s_fu_416_C_2_0_we0 );
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );

    SC_METHOD(thread_S_3_0_address0);
    sensitive << ( grp_inference_add_1_10_s_fu_416_C_3_0_address0 );
    sensitive << ( grp_inference_softmax_1_10_s_fu_430_A_3_0_address0 );
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );
    sensitive << ( ap_sig_cseq_ST_st6_fsm_5 );

    SC_METHOD(thread_S_3_0_ce0);
    sensitive << ( grp_inference_add_1_10_s_fu_416_C_3_0_ce0 );
    sensitive << ( grp_inference_softmax_1_10_s_fu_430_A_3_0_ce0 );
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );
    sensitive << ( ap_sig_cseq_ST_st6_fsm_5 );

    SC_METHOD(thread_S_3_0_d0);
    sensitive << ( grp_inference_add_1_10_s_fu_416_C_3_0_d0 );
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );

    SC_METHOD(thread_S_3_0_we0);
    sensitive << ( grp_inference_add_1_10_s_fu_416_C_3_0_we0 );
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );

    SC_METHOD(thread_T_0_0_address0);
    sensitive << ( grp_inference_mult_1_84_84_10_s_fu_228_C_0_0_address0 );
    sensitive << ( grp_inference_add_1_10_s_fu_416_A_0_0_address0 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );

    SC_METHOD(thread_T_0_0_ce0);
    sensitive << ( grp_inference_mult_1_84_84_10_s_fu_228_C_0_0_ce0 );
    sensitive << ( grp_inference_add_1_10_s_fu_416_A_0_0_ce0 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );

    SC_METHOD(thread_T_0_0_d0);
    sensitive << ( grp_inference_mult_1_84_84_10_s_fu_228_C_0_0_d0 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_T_0_0_we0);
    sensitive << ( grp_inference_mult_1_84_84_10_s_fu_228_C_0_0_we0 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_T_1_0_address0);
    sensitive << ( grp_inference_mult_1_84_84_10_s_fu_228_C_1_0_address0 );
    sensitive << ( grp_inference_add_1_10_s_fu_416_A_1_0_address0 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );

    SC_METHOD(thread_T_1_0_ce0);
    sensitive << ( grp_inference_mult_1_84_84_10_s_fu_228_C_1_0_ce0 );
    sensitive << ( grp_inference_add_1_10_s_fu_416_A_1_0_ce0 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );

    SC_METHOD(thread_T_1_0_d0);
    sensitive << ( grp_inference_mult_1_84_84_10_s_fu_228_C_1_0_d0 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_T_1_0_we0);
    sensitive << ( grp_inference_mult_1_84_84_10_s_fu_228_C_1_0_we0 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_T_2_0_address0);
    sensitive << ( grp_inference_mult_1_84_84_10_s_fu_228_C_2_0_address0 );
    sensitive << ( grp_inference_add_1_10_s_fu_416_A_2_0_address0 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );

    SC_METHOD(thread_T_2_0_ce0);
    sensitive << ( grp_inference_mult_1_84_84_10_s_fu_228_C_2_0_ce0 );
    sensitive << ( grp_inference_add_1_10_s_fu_416_A_2_0_ce0 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );

    SC_METHOD(thread_T_2_0_d0);
    sensitive << ( grp_inference_mult_1_84_84_10_s_fu_228_C_2_0_d0 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_T_2_0_we0);
    sensitive << ( grp_inference_mult_1_84_84_10_s_fu_228_C_2_0_we0 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_T_3_0_address0);
    sensitive << ( grp_inference_mult_1_84_84_10_s_fu_228_C_3_0_address0 );
    sensitive << ( grp_inference_add_1_10_s_fu_416_A_3_0_address0 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );

    SC_METHOD(thread_T_3_0_ce0);
    sensitive << ( grp_inference_mult_1_84_84_10_s_fu_228_C_3_0_ce0 );
    sensitive << ( grp_inference_add_1_10_s_fu_416_A_3_0_ce0 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );

    SC_METHOD(thread_T_3_0_d0);
    sensitive << ( grp_inference_mult_1_84_84_10_s_fu_228_C_3_0_d0 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_T_3_0_we0);
    sensitive << ( grp_inference_mult_1_84_84_10_s_fu_228_C_3_0_we0 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_X_0_0_address0);
    sensitive << ( grp_inference_mult_1_84_84_10_s_fu_228_A_0_0_address0 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_X_0_0_address1);
    sensitive << ( grp_inference_mult_1_84_84_10_s_fu_228_A_0_0_address1 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_X_0_0_ce0);
    sensitive << ( grp_inference_mult_1_84_84_10_s_fu_228_A_0_0_ce0 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_X_0_0_ce1);
    sensitive << ( grp_inference_mult_1_84_84_10_s_fu_228_A_0_0_ce1 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_X_1_0_address0);
    sensitive << ( grp_inference_mult_1_84_84_10_s_fu_228_A_1_0_address0 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_X_1_0_address1);
    sensitive << ( grp_inference_mult_1_84_84_10_s_fu_228_A_1_0_address1 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_X_1_0_ce0);
    sensitive << ( grp_inference_mult_1_84_84_10_s_fu_228_A_1_0_ce0 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_X_1_0_ce1);
    sensitive << ( grp_inference_mult_1_84_84_10_s_fu_228_A_1_0_ce1 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_X_2_0_address0);
    sensitive << ( grp_inference_mult_1_84_84_10_s_fu_228_A_2_0_address0 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_X_2_0_address1);
    sensitive << ( grp_inference_mult_1_84_84_10_s_fu_228_A_2_0_address1 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_X_2_0_ce0);
    sensitive << ( grp_inference_mult_1_84_84_10_s_fu_228_A_2_0_ce0 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_X_2_0_ce1);
    sensitive << ( grp_inference_mult_1_84_84_10_s_fu_228_A_2_0_ce1 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_X_3_0_address0);
    sensitive << ( grp_inference_mult_1_84_84_10_s_fu_228_A_3_0_address0 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_X_3_0_address1);
    sensitive << ( grp_inference_mult_1_84_84_10_s_fu_228_A_3_0_address1 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_X_3_0_ce0);
    sensitive << ( grp_inference_mult_1_84_84_10_s_fu_228_A_3_0_ce0 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_X_3_0_ce1);
    sensitive << ( grp_inference_mult_1_84_84_10_s_fu_228_A_3_0_ce1 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_done_reg );
    sensitive << ( grp_inference_softmax_1_10_s_fu_430_ap_done );
    sensitive << ( ap_sig_cseq_ST_st6_fsm_5 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( grp_inference_softmax_1_10_s_fu_430_ap_done );
    sensitive << ( ap_sig_cseq_ST_st6_fsm_5 );

    SC_METHOD(thread_ap_sig_bdd_25);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_251);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );

    SC_METHOD(thread_ap_sig_bdd_259);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_940);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_947);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_964);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_971);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_cseq_ST_st1_fsm_0);
    sensitive << ( ap_sig_bdd_25 );

    SC_METHOD(thread_ap_sig_cseq_ST_st2_fsm_1);
    sensitive << ( ap_sig_bdd_259 );

    SC_METHOD(thread_ap_sig_cseq_ST_st3_fsm_2);
    sensitive << ( ap_sig_bdd_940 );

    SC_METHOD(thread_ap_sig_cseq_ST_st4_fsm_3);
    sensitive << ( ap_sig_bdd_947 );

    SC_METHOD(thread_ap_sig_cseq_ST_st5_fsm_4);
    sensitive << ( ap_sig_bdd_964 );

    SC_METHOD(thread_ap_sig_cseq_ST_st6_fsm_5);
    sensitive << ( ap_sig_bdd_971 );

    SC_METHOD(thread_argmax_TDATA);
    sensitive << ( grp_inference_softmax_1_10_s_fu_430_argmax_TDATA );
    sensitive << ( grp_inference_softmax_1_10_s_fu_430_argmax_TVALID );
    sensitive << ( ap_sig_cseq_ST_st5_fsm_4 );
    sensitive << ( ap_sig_cseq_ST_st6_fsm_5 );

    SC_METHOD(thread_argmax_TVALID);
    sensitive << ( grp_inference_softmax_1_10_s_fu_430_argmax_TVALID );
    sensitive << ( ap_sig_cseq_ST_st5_fsm_4 );
    sensitive << ( ap_sig_cseq_ST_st6_fsm_5 );

    SC_METHOD(thread_grp_inference_add_1_10_s_fu_416_A_0_0_q0);
    sensitive << ( T_0_0_q0 );
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );

    SC_METHOD(thread_grp_inference_add_1_10_s_fu_416_A_1_0_q0);
    sensitive << ( T_1_0_q0 );
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );

    SC_METHOD(thread_grp_inference_add_1_10_s_fu_416_A_2_0_q0);
    sensitive << ( T_2_0_q0 );
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );

    SC_METHOD(thread_grp_inference_add_1_10_s_fu_416_A_3_0_q0);
    sensitive << ( T_3_0_q0 );
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );

    SC_METHOD(thread_grp_inference_add_1_10_s_fu_416_ap_start);
    sensitive << ( grp_inference_add_1_10_s_fu_416_ap_start_ap_start_reg );

    SC_METHOD(thread_grp_inference_mult_1_84_84_10_s_fu_228_A_0_0_q0);
    sensitive << ( X_0_0_q0 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_grp_inference_mult_1_84_84_10_s_fu_228_A_0_0_q1);
    sensitive << ( X_0_0_q1 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_grp_inference_mult_1_84_84_10_s_fu_228_A_1_0_q0);
    sensitive << ( X_1_0_q0 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_grp_inference_mult_1_84_84_10_s_fu_228_A_1_0_q1);
    sensitive << ( X_1_0_q1 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_grp_inference_mult_1_84_84_10_s_fu_228_A_2_0_q0);
    sensitive << ( X_2_0_q0 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_grp_inference_mult_1_84_84_10_s_fu_228_A_2_0_q1);
    sensitive << ( X_2_0_q1 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_grp_inference_mult_1_84_84_10_s_fu_228_A_3_0_q0);
    sensitive << ( X_3_0_q0 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_grp_inference_mult_1_84_84_10_s_fu_228_A_3_0_q1);
    sensitive << ( X_3_0_q1 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_grp_inference_mult_1_84_84_10_s_fu_228_ap_start);
    sensitive << ( grp_inference_mult_1_84_84_10_s_fu_228_ap_start_ap_start_reg );

    SC_METHOD(thread_grp_inference_softmax_1_10_s_fu_430_A_0_0_q0);
    sensitive << ( S_0_0_q0 );
    sensitive << ( ap_sig_cseq_ST_st6_fsm_5 );

    SC_METHOD(thread_grp_inference_softmax_1_10_s_fu_430_A_1_0_q0);
    sensitive << ( S_1_0_q0 );
    sensitive << ( ap_sig_cseq_ST_st6_fsm_5 );

    SC_METHOD(thread_grp_inference_softmax_1_10_s_fu_430_A_2_0_q0);
    sensitive << ( S_2_0_q0 );
    sensitive << ( ap_sig_cseq_ST_st6_fsm_5 );

    SC_METHOD(thread_grp_inference_softmax_1_10_s_fu_430_A_3_0_q0);
    sensitive << ( S_3_0_q0 );
    sensitive << ( ap_sig_cseq_ST_st6_fsm_5 );

    SC_METHOD(thread_grp_inference_softmax_1_10_s_fu_430_ap_start);
    sensitive << ( grp_inference_softmax_1_10_s_fu_430_ap_start_ap_start_reg );

    SC_METHOD(thread_grp_inference_softmax_1_10_s_fu_430_argmax_TREADY);
    sensitive << ( argmax_TREADY );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_CS_fsm );
    sensitive << ( grp_inference_mult_1_84_84_10_s_fu_228_ap_done );
    sensitive << ( grp_inference_add_1_10_s_fu_416_ap_done );
    sensitive << ( grp_inference_softmax_1_10_s_fu_430_ap_done );
    sensitive << ( ap_sig_bdd_251 );

    ap_done_reg = SC_LOGIC_0;
    ap_CS_fsm = "000001";
    grp_inference_mult_1_84_84_10_s_fu_228_ap_start_ap_start_reg = SC_LOGIC_0;
    grp_inference_add_1_10_s_fu_416_ap_start_ap_start_reg = SC_LOGIC_0;
    grp_inference_softmax_1_10_s_fu_430_ap_start_ap_start_reg = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "inference_sm_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_continue, "(port)ap_continue");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, X_0_0_address0, "(port)X_0_0_address0");
    sc_trace(mVcdFile, X_0_0_ce0, "(port)X_0_0_ce0");
    sc_trace(mVcdFile, X_0_0_q0, "(port)X_0_0_q0");
    sc_trace(mVcdFile, X_0_0_address1, "(port)X_0_0_address1");
    sc_trace(mVcdFile, X_0_0_ce1, "(port)X_0_0_ce1");
    sc_trace(mVcdFile, X_0_0_q1, "(port)X_0_0_q1");
    sc_trace(mVcdFile, X_1_0_address0, "(port)X_1_0_address0");
    sc_trace(mVcdFile, X_1_0_ce0, "(port)X_1_0_ce0");
    sc_trace(mVcdFile, X_1_0_q0, "(port)X_1_0_q0");
    sc_trace(mVcdFile, X_1_0_address1, "(port)X_1_0_address1");
    sc_trace(mVcdFile, X_1_0_ce1, "(port)X_1_0_ce1");
    sc_trace(mVcdFile, X_1_0_q1, "(port)X_1_0_q1");
    sc_trace(mVcdFile, X_2_0_address0, "(port)X_2_0_address0");
    sc_trace(mVcdFile, X_2_0_ce0, "(port)X_2_0_ce0");
    sc_trace(mVcdFile, X_2_0_q0, "(port)X_2_0_q0");
    sc_trace(mVcdFile, X_2_0_address1, "(port)X_2_0_address1");
    sc_trace(mVcdFile, X_2_0_ce1, "(port)X_2_0_ce1");
    sc_trace(mVcdFile, X_2_0_q1, "(port)X_2_0_q1");
    sc_trace(mVcdFile, X_3_0_address0, "(port)X_3_0_address0");
    sc_trace(mVcdFile, X_3_0_ce0, "(port)X_3_0_ce0");
    sc_trace(mVcdFile, X_3_0_q0, "(port)X_3_0_q0");
    sc_trace(mVcdFile, X_3_0_address1, "(port)X_3_0_address1");
    sc_trace(mVcdFile, X_3_0_ce1, "(port)X_3_0_ce1");
    sc_trace(mVcdFile, X_3_0_q1, "(port)X_3_0_q1");
    sc_trace(mVcdFile, argmax_TDATA, "(port)argmax_TDATA");
    sc_trace(mVcdFile, argmax_TVALID, "(port)argmax_TVALID");
    sc_trace(mVcdFile, argmax_TREADY, "(port)argmax_TREADY");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_done_reg, "ap_done_reg");
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st1_fsm_0, "ap_sig_cseq_ST_st1_fsm_0");
    sc_trace(mVcdFile, ap_sig_bdd_25, "ap_sig_bdd_25");
    sc_trace(mVcdFile, T_0_0_address0, "T_0_0_address0");
    sc_trace(mVcdFile, T_0_0_ce0, "T_0_0_ce0");
    sc_trace(mVcdFile, T_0_0_we0, "T_0_0_we0");
    sc_trace(mVcdFile, T_0_0_d0, "T_0_0_d0");
    sc_trace(mVcdFile, T_0_0_q0, "T_0_0_q0");
    sc_trace(mVcdFile, T_1_0_address0, "T_1_0_address0");
    sc_trace(mVcdFile, T_1_0_ce0, "T_1_0_ce0");
    sc_trace(mVcdFile, T_1_0_we0, "T_1_0_we0");
    sc_trace(mVcdFile, T_1_0_d0, "T_1_0_d0");
    sc_trace(mVcdFile, T_1_0_q0, "T_1_0_q0");
    sc_trace(mVcdFile, T_2_0_address0, "T_2_0_address0");
    sc_trace(mVcdFile, T_2_0_ce0, "T_2_0_ce0");
    sc_trace(mVcdFile, T_2_0_we0, "T_2_0_we0");
    sc_trace(mVcdFile, T_2_0_d0, "T_2_0_d0");
    sc_trace(mVcdFile, T_2_0_q0, "T_2_0_q0");
    sc_trace(mVcdFile, T_3_0_address0, "T_3_0_address0");
    sc_trace(mVcdFile, T_3_0_ce0, "T_3_0_ce0");
    sc_trace(mVcdFile, T_3_0_we0, "T_3_0_we0");
    sc_trace(mVcdFile, T_3_0_d0, "T_3_0_d0");
    sc_trace(mVcdFile, T_3_0_q0, "T_3_0_q0");
    sc_trace(mVcdFile, S_0_0_address0, "S_0_0_address0");
    sc_trace(mVcdFile, S_0_0_ce0, "S_0_0_ce0");
    sc_trace(mVcdFile, S_0_0_we0, "S_0_0_we0");
    sc_trace(mVcdFile, S_0_0_d0, "S_0_0_d0");
    sc_trace(mVcdFile, S_0_0_q0, "S_0_0_q0");
    sc_trace(mVcdFile, S_1_0_address0, "S_1_0_address0");
    sc_trace(mVcdFile, S_1_0_ce0, "S_1_0_ce0");
    sc_trace(mVcdFile, S_1_0_we0, "S_1_0_we0");
    sc_trace(mVcdFile, S_1_0_d0, "S_1_0_d0");
    sc_trace(mVcdFile, S_1_0_q0, "S_1_0_q0");
    sc_trace(mVcdFile, S_2_0_address0, "S_2_0_address0");
    sc_trace(mVcdFile, S_2_0_ce0, "S_2_0_ce0");
    sc_trace(mVcdFile, S_2_0_we0, "S_2_0_we0");
    sc_trace(mVcdFile, S_2_0_d0, "S_2_0_d0");
    sc_trace(mVcdFile, S_2_0_q0, "S_2_0_q0");
    sc_trace(mVcdFile, S_3_0_address0, "S_3_0_address0");
    sc_trace(mVcdFile, S_3_0_ce0, "S_3_0_ce0");
    sc_trace(mVcdFile, S_3_0_we0, "S_3_0_we0");
    sc_trace(mVcdFile, S_3_0_d0, "S_3_0_d0");
    sc_trace(mVcdFile, S_3_0_q0, "S_3_0_q0");
    sc_trace(mVcdFile, grp_inference_mult_1_84_84_10_s_fu_228_ap_start, "grp_inference_mult_1_84_84_10_s_fu_228_ap_start");
    sc_trace(mVcdFile, grp_inference_mult_1_84_84_10_s_fu_228_ap_done, "grp_inference_mult_1_84_84_10_s_fu_228_ap_done");
    sc_trace(mVcdFile, grp_inference_mult_1_84_84_10_s_fu_228_ap_idle, "grp_inference_mult_1_84_84_10_s_fu_228_ap_idle");
    sc_trace(mVcdFile, grp_inference_mult_1_84_84_10_s_fu_228_ap_ready, "grp_inference_mult_1_84_84_10_s_fu_228_ap_ready");
    sc_trace(mVcdFile, grp_inference_mult_1_84_84_10_s_fu_228_A_0_0_address0, "grp_inference_mult_1_84_84_10_s_fu_228_A_0_0_address0");
    sc_trace(mVcdFile, grp_inference_mult_1_84_84_10_s_fu_228_A_0_0_ce0, "grp_inference_mult_1_84_84_10_s_fu_228_A_0_0_ce0");
    sc_trace(mVcdFile, grp_inference_mult_1_84_84_10_s_fu_228_A_0_0_q0, "grp_inference_mult_1_84_84_10_s_fu_228_A_0_0_q0");
    sc_trace(mVcdFile, grp_inference_mult_1_84_84_10_s_fu_228_A_0_0_address1, "grp_inference_mult_1_84_84_10_s_fu_228_A_0_0_address1");
    sc_trace(mVcdFile, grp_inference_mult_1_84_84_10_s_fu_228_A_0_0_ce1, "grp_inference_mult_1_84_84_10_s_fu_228_A_0_0_ce1");
    sc_trace(mVcdFile, grp_inference_mult_1_84_84_10_s_fu_228_A_0_0_q1, "grp_inference_mult_1_84_84_10_s_fu_228_A_0_0_q1");
    sc_trace(mVcdFile, grp_inference_mult_1_84_84_10_s_fu_228_A_1_0_address0, "grp_inference_mult_1_84_84_10_s_fu_228_A_1_0_address0");
    sc_trace(mVcdFile, grp_inference_mult_1_84_84_10_s_fu_228_A_1_0_ce0, "grp_inference_mult_1_84_84_10_s_fu_228_A_1_0_ce0");
    sc_trace(mVcdFile, grp_inference_mult_1_84_84_10_s_fu_228_A_1_0_q0, "grp_inference_mult_1_84_84_10_s_fu_228_A_1_0_q0");
    sc_trace(mVcdFile, grp_inference_mult_1_84_84_10_s_fu_228_A_1_0_address1, "grp_inference_mult_1_84_84_10_s_fu_228_A_1_0_address1");
    sc_trace(mVcdFile, grp_inference_mult_1_84_84_10_s_fu_228_A_1_0_ce1, "grp_inference_mult_1_84_84_10_s_fu_228_A_1_0_ce1");
    sc_trace(mVcdFile, grp_inference_mult_1_84_84_10_s_fu_228_A_1_0_q1, "grp_inference_mult_1_84_84_10_s_fu_228_A_1_0_q1");
    sc_trace(mVcdFile, grp_inference_mult_1_84_84_10_s_fu_228_A_2_0_address0, "grp_inference_mult_1_84_84_10_s_fu_228_A_2_0_address0");
    sc_trace(mVcdFile, grp_inference_mult_1_84_84_10_s_fu_228_A_2_0_ce0, "grp_inference_mult_1_84_84_10_s_fu_228_A_2_0_ce0");
    sc_trace(mVcdFile, grp_inference_mult_1_84_84_10_s_fu_228_A_2_0_q0, "grp_inference_mult_1_84_84_10_s_fu_228_A_2_0_q0");
    sc_trace(mVcdFile, grp_inference_mult_1_84_84_10_s_fu_228_A_2_0_address1, "grp_inference_mult_1_84_84_10_s_fu_228_A_2_0_address1");
    sc_trace(mVcdFile, grp_inference_mult_1_84_84_10_s_fu_228_A_2_0_ce1, "grp_inference_mult_1_84_84_10_s_fu_228_A_2_0_ce1");
    sc_trace(mVcdFile, grp_inference_mult_1_84_84_10_s_fu_228_A_2_0_q1, "grp_inference_mult_1_84_84_10_s_fu_228_A_2_0_q1");
    sc_trace(mVcdFile, grp_inference_mult_1_84_84_10_s_fu_228_A_3_0_address0, "grp_inference_mult_1_84_84_10_s_fu_228_A_3_0_address0");
    sc_trace(mVcdFile, grp_inference_mult_1_84_84_10_s_fu_228_A_3_0_ce0, "grp_inference_mult_1_84_84_10_s_fu_228_A_3_0_ce0");
    sc_trace(mVcdFile, grp_inference_mult_1_84_84_10_s_fu_228_A_3_0_q0, "grp_inference_mult_1_84_84_10_s_fu_228_A_3_0_q0");
    sc_trace(mVcdFile, grp_inference_mult_1_84_84_10_s_fu_228_A_3_0_address1, "grp_inference_mult_1_84_84_10_s_fu_228_A_3_0_address1");
    sc_trace(mVcdFile, grp_inference_mult_1_84_84_10_s_fu_228_A_3_0_ce1, "grp_inference_mult_1_84_84_10_s_fu_228_A_3_0_ce1");
    sc_trace(mVcdFile, grp_inference_mult_1_84_84_10_s_fu_228_A_3_0_q1, "grp_inference_mult_1_84_84_10_s_fu_228_A_3_0_q1");
    sc_trace(mVcdFile, grp_inference_mult_1_84_84_10_s_fu_228_C_0_0_address0, "grp_inference_mult_1_84_84_10_s_fu_228_C_0_0_address0");
    sc_trace(mVcdFile, grp_inference_mult_1_84_84_10_s_fu_228_C_0_0_ce0, "grp_inference_mult_1_84_84_10_s_fu_228_C_0_0_ce0");
    sc_trace(mVcdFile, grp_inference_mult_1_84_84_10_s_fu_228_C_0_0_we0, "grp_inference_mult_1_84_84_10_s_fu_228_C_0_0_we0");
    sc_trace(mVcdFile, grp_inference_mult_1_84_84_10_s_fu_228_C_0_0_d0, "grp_inference_mult_1_84_84_10_s_fu_228_C_0_0_d0");
    sc_trace(mVcdFile, grp_inference_mult_1_84_84_10_s_fu_228_C_1_0_address0, "grp_inference_mult_1_84_84_10_s_fu_228_C_1_0_address0");
    sc_trace(mVcdFile, grp_inference_mult_1_84_84_10_s_fu_228_C_1_0_ce0, "grp_inference_mult_1_84_84_10_s_fu_228_C_1_0_ce0");
    sc_trace(mVcdFile, grp_inference_mult_1_84_84_10_s_fu_228_C_1_0_we0, "grp_inference_mult_1_84_84_10_s_fu_228_C_1_0_we0");
    sc_trace(mVcdFile, grp_inference_mult_1_84_84_10_s_fu_228_C_1_0_d0, "grp_inference_mult_1_84_84_10_s_fu_228_C_1_0_d0");
    sc_trace(mVcdFile, grp_inference_mult_1_84_84_10_s_fu_228_C_2_0_address0, "grp_inference_mult_1_84_84_10_s_fu_228_C_2_0_address0");
    sc_trace(mVcdFile, grp_inference_mult_1_84_84_10_s_fu_228_C_2_0_ce0, "grp_inference_mult_1_84_84_10_s_fu_228_C_2_0_ce0");
    sc_trace(mVcdFile, grp_inference_mult_1_84_84_10_s_fu_228_C_2_0_we0, "grp_inference_mult_1_84_84_10_s_fu_228_C_2_0_we0");
    sc_trace(mVcdFile, grp_inference_mult_1_84_84_10_s_fu_228_C_2_0_d0, "grp_inference_mult_1_84_84_10_s_fu_228_C_2_0_d0");
    sc_trace(mVcdFile, grp_inference_mult_1_84_84_10_s_fu_228_C_3_0_address0, "grp_inference_mult_1_84_84_10_s_fu_228_C_3_0_address0");
    sc_trace(mVcdFile, grp_inference_mult_1_84_84_10_s_fu_228_C_3_0_ce0, "grp_inference_mult_1_84_84_10_s_fu_228_C_3_0_ce0");
    sc_trace(mVcdFile, grp_inference_mult_1_84_84_10_s_fu_228_C_3_0_we0, "grp_inference_mult_1_84_84_10_s_fu_228_C_3_0_we0");
    sc_trace(mVcdFile, grp_inference_mult_1_84_84_10_s_fu_228_C_3_0_d0, "grp_inference_mult_1_84_84_10_s_fu_228_C_3_0_d0");
    sc_trace(mVcdFile, grp_inference_add_1_10_s_fu_416_ap_start, "grp_inference_add_1_10_s_fu_416_ap_start");
    sc_trace(mVcdFile, grp_inference_add_1_10_s_fu_416_ap_done, "grp_inference_add_1_10_s_fu_416_ap_done");
    sc_trace(mVcdFile, grp_inference_add_1_10_s_fu_416_ap_idle, "grp_inference_add_1_10_s_fu_416_ap_idle");
    sc_trace(mVcdFile, grp_inference_add_1_10_s_fu_416_ap_ready, "grp_inference_add_1_10_s_fu_416_ap_ready");
    sc_trace(mVcdFile, grp_inference_add_1_10_s_fu_416_A_0_0_address0, "grp_inference_add_1_10_s_fu_416_A_0_0_address0");
    sc_trace(mVcdFile, grp_inference_add_1_10_s_fu_416_A_0_0_ce0, "grp_inference_add_1_10_s_fu_416_A_0_0_ce0");
    sc_trace(mVcdFile, grp_inference_add_1_10_s_fu_416_A_0_0_q0, "grp_inference_add_1_10_s_fu_416_A_0_0_q0");
    sc_trace(mVcdFile, grp_inference_add_1_10_s_fu_416_A_1_0_address0, "grp_inference_add_1_10_s_fu_416_A_1_0_address0");
    sc_trace(mVcdFile, grp_inference_add_1_10_s_fu_416_A_1_0_ce0, "grp_inference_add_1_10_s_fu_416_A_1_0_ce0");
    sc_trace(mVcdFile, grp_inference_add_1_10_s_fu_416_A_1_0_q0, "grp_inference_add_1_10_s_fu_416_A_1_0_q0");
    sc_trace(mVcdFile, grp_inference_add_1_10_s_fu_416_A_2_0_address0, "grp_inference_add_1_10_s_fu_416_A_2_0_address0");
    sc_trace(mVcdFile, grp_inference_add_1_10_s_fu_416_A_2_0_ce0, "grp_inference_add_1_10_s_fu_416_A_2_0_ce0");
    sc_trace(mVcdFile, grp_inference_add_1_10_s_fu_416_A_2_0_q0, "grp_inference_add_1_10_s_fu_416_A_2_0_q0");
    sc_trace(mVcdFile, grp_inference_add_1_10_s_fu_416_A_3_0_address0, "grp_inference_add_1_10_s_fu_416_A_3_0_address0");
    sc_trace(mVcdFile, grp_inference_add_1_10_s_fu_416_A_3_0_ce0, "grp_inference_add_1_10_s_fu_416_A_3_0_ce0");
    sc_trace(mVcdFile, grp_inference_add_1_10_s_fu_416_A_3_0_q0, "grp_inference_add_1_10_s_fu_416_A_3_0_q0");
    sc_trace(mVcdFile, grp_inference_add_1_10_s_fu_416_C_0_0_address0, "grp_inference_add_1_10_s_fu_416_C_0_0_address0");
    sc_trace(mVcdFile, grp_inference_add_1_10_s_fu_416_C_0_0_ce0, "grp_inference_add_1_10_s_fu_416_C_0_0_ce0");
    sc_trace(mVcdFile, grp_inference_add_1_10_s_fu_416_C_0_0_we0, "grp_inference_add_1_10_s_fu_416_C_0_0_we0");
    sc_trace(mVcdFile, grp_inference_add_1_10_s_fu_416_C_0_0_d0, "grp_inference_add_1_10_s_fu_416_C_0_0_d0");
    sc_trace(mVcdFile, grp_inference_add_1_10_s_fu_416_C_1_0_address0, "grp_inference_add_1_10_s_fu_416_C_1_0_address0");
    sc_trace(mVcdFile, grp_inference_add_1_10_s_fu_416_C_1_0_ce0, "grp_inference_add_1_10_s_fu_416_C_1_0_ce0");
    sc_trace(mVcdFile, grp_inference_add_1_10_s_fu_416_C_1_0_we0, "grp_inference_add_1_10_s_fu_416_C_1_0_we0");
    sc_trace(mVcdFile, grp_inference_add_1_10_s_fu_416_C_1_0_d0, "grp_inference_add_1_10_s_fu_416_C_1_0_d0");
    sc_trace(mVcdFile, grp_inference_add_1_10_s_fu_416_C_2_0_address0, "grp_inference_add_1_10_s_fu_416_C_2_0_address0");
    sc_trace(mVcdFile, grp_inference_add_1_10_s_fu_416_C_2_0_ce0, "grp_inference_add_1_10_s_fu_416_C_2_0_ce0");
    sc_trace(mVcdFile, grp_inference_add_1_10_s_fu_416_C_2_0_we0, "grp_inference_add_1_10_s_fu_416_C_2_0_we0");
    sc_trace(mVcdFile, grp_inference_add_1_10_s_fu_416_C_2_0_d0, "grp_inference_add_1_10_s_fu_416_C_2_0_d0");
    sc_trace(mVcdFile, grp_inference_add_1_10_s_fu_416_C_3_0_address0, "grp_inference_add_1_10_s_fu_416_C_3_0_address0");
    sc_trace(mVcdFile, grp_inference_add_1_10_s_fu_416_C_3_0_ce0, "grp_inference_add_1_10_s_fu_416_C_3_0_ce0");
    sc_trace(mVcdFile, grp_inference_add_1_10_s_fu_416_C_3_0_we0, "grp_inference_add_1_10_s_fu_416_C_3_0_we0");
    sc_trace(mVcdFile, grp_inference_add_1_10_s_fu_416_C_3_0_d0, "grp_inference_add_1_10_s_fu_416_C_3_0_d0");
    sc_trace(mVcdFile, grp_inference_softmax_1_10_s_fu_430_ap_start, "grp_inference_softmax_1_10_s_fu_430_ap_start");
    sc_trace(mVcdFile, grp_inference_softmax_1_10_s_fu_430_ap_done, "grp_inference_softmax_1_10_s_fu_430_ap_done");
    sc_trace(mVcdFile, grp_inference_softmax_1_10_s_fu_430_ap_idle, "grp_inference_softmax_1_10_s_fu_430_ap_idle");
    sc_trace(mVcdFile, grp_inference_softmax_1_10_s_fu_430_ap_ready, "grp_inference_softmax_1_10_s_fu_430_ap_ready");
    sc_trace(mVcdFile, grp_inference_softmax_1_10_s_fu_430_A_0_0_address0, "grp_inference_softmax_1_10_s_fu_430_A_0_0_address0");
    sc_trace(mVcdFile, grp_inference_softmax_1_10_s_fu_430_A_0_0_ce0, "grp_inference_softmax_1_10_s_fu_430_A_0_0_ce0");
    sc_trace(mVcdFile, grp_inference_softmax_1_10_s_fu_430_A_0_0_q0, "grp_inference_softmax_1_10_s_fu_430_A_0_0_q0");
    sc_trace(mVcdFile, grp_inference_softmax_1_10_s_fu_430_A_1_0_address0, "grp_inference_softmax_1_10_s_fu_430_A_1_0_address0");
    sc_trace(mVcdFile, grp_inference_softmax_1_10_s_fu_430_A_1_0_ce0, "grp_inference_softmax_1_10_s_fu_430_A_1_0_ce0");
    sc_trace(mVcdFile, grp_inference_softmax_1_10_s_fu_430_A_1_0_q0, "grp_inference_softmax_1_10_s_fu_430_A_1_0_q0");
    sc_trace(mVcdFile, grp_inference_softmax_1_10_s_fu_430_A_2_0_address0, "grp_inference_softmax_1_10_s_fu_430_A_2_0_address0");
    sc_trace(mVcdFile, grp_inference_softmax_1_10_s_fu_430_A_2_0_ce0, "grp_inference_softmax_1_10_s_fu_430_A_2_0_ce0");
    sc_trace(mVcdFile, grp_inference_softmax_1_10_s_fu_430_A_2_0_q0, "grp_inference_softmax_1_10_s_fu_430_A_2_0_q0");
    sc_trace(mVcdFile, grp_inference_softmax_1_10_s_fu_430_A_3_0_address0, "grp_inference_softmax_1_10_s_fu_430_A_3_0_address0");
    sc_trace(mVcdFile, grp_inference_softmax_1_10_s_fu_430_A_3_0_ce0, "grp_inference_softmax_1_10_s_fu_430_A_3_0_ce0");
    sc_trace(mVcdFile, grp_inference_softmax_1_10_s_fu_430_A_3_0_q0, "grp_inference_softmax_1_10_s_fu_430_A_3_0_q0");
    sc_trace(mVcdFile, grp_inference_softmax_1_10_s_fu_430_argmax_TDATA, "grp_inference_softmax_1_10_s_fu_430_argmax_TDATA");
    sc_trace(mVcdFile, grp_inference_softmax_1_10_s_fu_430_argmax_TVALID, "grp_inference_softmax_1_10_s_fu_430_argmax_TVALID");
    sc_trace(mVcdFile, grp_inference_softmax_1_10_s_fu_430_argmax_TREADY, "grp_inference_softmax_1_10_s_fu_430_argmax_TREADY");
    sc_trace(mVcdFile, grp_inference_mult_1_84_84_10_s_fu_228_ap_start_ap_start_reg, "grp_inference_mult_1_84_84_10_s_fu_228_ap_start_ap_start_reg");
    sc_trace(mVcdFile, ap_sig_bdd_251, "ap_sig_bdd_251");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st2_fsm_1, "ap_sig_cseq_ST_st2_fsm_1");
    sc_trace(mVcdFile, ap_sig_bdd_259, "ap_sig_bdd_259");
    sc_trace(mVcdFile, grp_inference_add_1_10_s_fu_416_ap_start_ap_start_reg, "grp_inference_add_1_10_s_fu_416_ap_start_ap_start_reg");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st3_fsm_2, "ap_sig_cseq_ST_st3_fsm_2");
    sc_trace(mVcdFile, ap_sig_bdd_940, "ap_sig_bdd_940");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st4_fsm_3, "ap_sig_cseq_ST_st4_fsm_3");
    sc_trace(mVcdFile, ap_sig_bdd_947, "ap_sig_bdd_947");
    sc_trace(mVcdFile, grp_inference_softmax_1_10_s_fu_430_ap_start_ap_start_reg, "grp_inference_softmax_1_10_s_fu_430_ap_start_ap_start_reg");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st5_fsm_4, "ap_sig_cseq_ST_st5_fsm_4");
    sc_trace(mVcdFile, ap_sig_bdd_964, "ap_sig_bdd_964");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st6_fsm_5, "ap_sig_cseq_ST_st6_fsm_5");
    sc_trace(mVcdFile, ap_sig_bdd_971, "ap_sig_bdd_971");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
}

inference_sm::~inference_sm() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete T_0_0_U;
    delete T_1_0_U;
    delete T_2_0_U;
    delete T_3_0_U;
    delete S_0_0_U;
    delete S_1_0_U;
    delete S_2_0_U;
    delete S_3_0_U;
    delete grp_inference_mult_1_84_84_10_s_fu_228;
    delete grp_inference_add_1_10_s_fu_416;
    delete grp_inference_softmax_1_10_s_fu_430;
}

void inference_sm::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_st1_fsm_0;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_done_reg = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_continue.read())) {
            ap_done_reg = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st6_fsm_5.read()) && 
                    !esl_seteq<1,1,1>(ap_const_logic_0, grp_inference_softmax_1_10_s_fu_430_ap_done.read()))) {
            ap_done_reg = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        grp_inference_add_1_10_s_fu_416_ap_start_ap_start_reg = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read())) {
            grp_inference_add_1_10_s_fu_416_ap_start_ap_start_reg = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_inference_add_1_10_s_fu_416_ap_ready.read())) {
            grp_inference_add_1_10_s_fu_416_ap_start_ap_start_reg = ap_const_logic_0;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        grp_inference_mult_1_84_84_10_s_fu_228_ap_start_ap_start_reg = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
             !ap_sig_bdd_251.read())) {
            grp_inference_mult_1_84_84_10_s_fu_228_ap_start_ap_start_reg = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_inference_mult_1_84_84_10_s_fu_228_ap_ready.read())) {
            grp_inference_mult_1_84_84_10_s_fu_228_ap_start_ap_start_reg = ap_const_logic_0;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        grp_inference_softmax_1_10_s_fu_430_ap_start_ap_start_reg = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st5_fsm_4.read())) {
            grp_inference_softmax_1_10_s_fu_430_ap_start_ap_start_reg = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_inference_softmax_1_10_s_fu_430_ap_ready.read())) {
            grp_inference_softmax_1_10_s_fu_430_ap_start_ap_start_reg = ap_const_logic_0;
        }
    }
}

void inference_sm::thread_S_0_0_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st6_fsm_5.read())) {
        S_0_0_address0 = grp_inference_softmax_1_10_s_fu_430_A_0_0_address0.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read())) {
        S_0_0_address0 = grp_inference_add_1_10_s_fu_416_C_0_0_address0.read();
    } else {
        S_0_0_address0 = "XX";
    }
}

void inference_sm::thread_S_0_0_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st6_fsm_5.read())) {
        S_0_0_ce0 = grp_inference_softmax_1_10_s_fu_430_A_0_0_ce0.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read())) {
        S_0_0_ce0 = grp_inference_add_1_10_s_fu_416_C_0_0_ce0.read();
    } else {
        S_0_0_ce0 = ap_const_logic_0;
    }
}

void inference_sm::thread_S_0_0_d0() {
    S_0_0_d0 = grp_inference_add_1_10_s_fu_416_C_0_0_d0.read();
}

void inference_sm::thread_S_0_0_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read())) {
        S_0_0_we0 = grp_inference_add_1_10_s_fu_416_C_0_0_we0.read();
    } else {
        S_0_0_we0 = ap_const_logic_0;
    }
}

void inference_sm::thread_S_1_0_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st6_fsm_5.read())) {
        S_1_0_address0 = grp_inference_softmax_1_10_s_fu_430_A_1_0_address0.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read())) {
        S_1_0_address0 = grp_inference_add_1_10_s_fu_416_C_1_0_address0.read();
    } else {
        S_1_0_address0 = "XX";
    }
}

void inference_sm::thread_S_1_0_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st6_fsm_5.read())) {
        S_1_0_ce0 = grp_inference_softmax_1_10_s_fu_430_A_1_0_ce0.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read())) {
        S_1_0_ce0 = grp_inference_add_1_10_s_fu_416_C_1_0_ce0.read();
    } else {
        S_1_0_ce0 = ap_const_logic_0;
    }
}

void inference_sm::thread_S_1_0_d0() {
    S_1_0_d0 = grp_inference_add_1_10_s_fu_416_C_1_0_d0.read();
}

void inference_sm::thread_S_1_0_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read())) {
        S_1_0_we0 = grp_inference_add_1_10_s_fu_416_C_1_0_we0.read();
    } else {
        S_1_0_we0 = ap_const_logic_0;
    }
}

void inference_sm::thread_S_2_0_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st6_fsm_5.read())) {
        S_2_0_address0 = grp_inference_softmax_1_10_s_fu_430_A_2_0_address0.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read())) {
        S_2_0_address0 = grp_inference_add_1_10_s_fu_416_C_2_0_address0.read();
    } else {
        S_2_0_address0 =  (sc_lv<1>) ("X");
    }
}

void inference_sm::thread_S_2_0_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st6_fsm_5.read())) {
        S_2_0_ce0 = grp_inference_softmax_1_10_s_fu_430_A_2_0_ce0.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read())) {
        S_2_0_ce0 = grp_inference_add_1_10_s_fu_416_C_2_0_ce0.read();
    } else {
        S_2_0_ce0 = ap_const_logic_0;
    }
}

void inference_sm::thread_S_2_0_d0() {
    S_2_0_d0 = grp_inference_add_1_10_s_fu_416_C_2_0_d0.read();
}

void inference_sm::thread_S_2_0_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read())) {
        S_2_0_we0 = grp_inference_add_1_10_s_fu_416_C_2_0_we0.read();
    } else {
        S_2_0_we0 = ap_const_logic_0;
    }
}

void inference_sm::thread_S_3_0_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st6_fsm_5.read())) {
        S_3_0_address0 = grp_inference_softmax_1_10_s_fu_430_A_3_0_address0.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read())) {
        S_3_0_address0 = grp_inference_add_1_10_s_fu_416_C_3_0_address0.read();
    } else {
        S_3_0_address0 =  (sc_lv<1>) ("X");
    }
}

void inference_sm::thread_S_3_0_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st6_fsm_5.read())) {
        S_3_0_ce0 = grp_inference_softmax_1_10_s_fu_430_A_3_0_ce0.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read())) {
        S_3_0_ce0 = grp_inference_add_1_10_s_fu_416_C_3_0_ce0.read();
    } else {
        S_3_0_ce0 = ap_const_logic_0;
    }
}

void inference_sm::thread_S_3_0_d0() {
    S_3_0_d0 = grp_inference_add_1_10_s_fu_416_C_3_0_d0.read();
}

void inference_sm::thread_S_3_0_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read())) {
        S_3_0_we0 = grp_inference_add_1_10_s_fu_416_C_3_0_we0.read();
    } else {
        S_3_0_we0 = ap_const_logic_0;
    }
}

void inference_sm::thread_T_0_0_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read())) {
        T_0_0_address0 = grp_inference_add_1_10_s_fu_416_A_0_0_address0.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read())) {
        T_0_0_address0 = grp_inference_mult_1_84_84_10_s_fu_228_C_0_0_address0.read();
    } else {
        T_0_0_address0 = "XX";
    }
}

void inference_sm::thread_T_0_0_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read())) {
        T_0_0_ce0 = grp_inference_add_1_10_s_fu_416_A_0_0_ce0.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read())) {
        T_0_0_ce0 = grp_inference_mult_1_84_84_10_s_fu_228_C_0_0_ce0.read();
    } else {
        T_0_0_ce0 = ap_const_logic_0;
    }
}

void inference_sm::thread_T_0_0_d0() {
    T_0_0_d0 = grp_inference_mult_1_84_84_10_s_fu_228_C_0_0_d0.read();
}

void inference_sm::thread_T_0_0_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read())) {
        T_0_0_we0 = grp_inference_mult_1_84_84_10_s_fu_228_C_0_0_we0.read();
    } else {
        T_0_0_we0 = ap_const_logic_0;
    }
}

void inference_sm::thread_T_1_0_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read())) {
        T_1_0_address0 = grp_inference_add_1_10_s_fu_416_A_1_0_address0.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read())) {
        T_1_0_address0 = grp_inference_mult_1_84_84_10_s_fu_228_C_1_0_address0.read();
    } else {
        T_1_0_address0 = "XX";
    }
}

void inference_sm::thread_T_1_0_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read())) {
        T_1_0_ce0 = grp_inference_add_1_10_s_fu_416_A_1_0_ce0.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read())) {
        T_1_0_ce0 = grp_inference_mult_1_84_84_10_s_fu_228_C_1_0_ce0.read();
    } else {
        T_1_0_ce0 = ap_const_logic_0;
    }
}

void inference_sm::thread_T_1_0_d0() {
    T_1_0_d0 = grp_inference_mult_1_84_84_10_s_fu_228_C_1_0_d0.read();
}

void inference_sm::thread_T_1_0_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read())) {
        T_1_0_we0 = grp_inference_mult_1_84_84_10_s_fu_228_C_1_0_we0.read();
    } else {
        T_1_0_we0 = ap_const_logic_0;
    }
}

void inference_sm::thread_T_2_0_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read())) {
        T_2_0_address0 = grp_inference_add_1_10_s_fu_416_A_2_0_address0.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read())) {
        T_2_0_address0 = grp_inference_mult_1_84_84_10_s_fu_228_C_2_0_address0.read();
    } else {
        T_2_0_address0 =  (sc_lv<1>) ("X");
    }
}

void inference_sm::thread_T_2_0_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read())) {
        T_2_0_ce0 = grp_inference_add_1_10_s_fu_416_A_2_0_ce0.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read())) {
        T_2_0_ce0 = grp_inference_mult_1_84_84_10_s_fu_228_C_2_0_ce0.read();
    } else {
        T_2_0_ce0 = ap_const_logic_0;
    }
}

void inference_sm::thread_T_2_0_d0() {
    T_2_0_d0 = grp_inference_mult_1_84_84_10_s_fu_228_C_2_0_d0.read();
}

void inference_sm::thread_T_2_0_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read())) {
        T_2_0_we0 = grp_inference_mult_1_84_84_10_s_fu_228_C_2_0_we0.read();
    } else {
        T_2_0_we0 = ap_const_logic_0;
    }
}

void inference_sm::thread_T_3_0_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read())) {
        T_3_0_address0 = grp_inference_add_1_10_s_fu_416_A_3_0_address0.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read())) {
        T_3_0_address0 = grp_inference_mult_1_84_84_10_s_fu_228_C_3_0_address0.read();
    } else {
        T_3_0_address0 =  (sc_lv<1>) ("X");
    }
}

void inference_sm::thread_T_3_0_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read())) {
        T_3_0_ce0 = grp_inference_add_1_10_s_fu_416_A_3_0_ce0.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read())) {
        T_3_0_ce0 = grp_inference_mult_1_84_84_10_s_fu_228_C_3_0_ce0.read();
    } else {
        T_3_0_ce0 = ap_const_logic_0;
    }
}

void inference_sm::thread_T_3_0_d0() {
    T_3_0_d0 = grp_inference_mult_1_84_84_10_s_fu_228_C_3_0_d0.read();
}

void inference_sm::thread_T_3_0_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read())) {
        T_3_0_we0 = grp_inference_mult_1_84_84_10_s_fu_228_C_3_0_we0.read();
    } else {
        T_3_0_we0 = ap_const_logic_0;
    }
}

void inference_sm::thread_X_0_0_address0() {
    X_0_0_address0 = grp_inference_mult_1_84_84_10_s_fu_228_A_0_0_address0.read();
}

void inference_sm::thread_X_0_0_address1() {
    X_0_0_address1 = grp_inference_mult_1_84_84_10_s_fu_228_A_0_0_address1.read();
}

void inference_sm::thread_X_0_0_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read())) {
        X_0_0_ce0 = grp_inference_mult_1_84_84_10_s_fu_228_A_0_0_ce0.read();
    } else {
        X_0_0_ce0 = ap_const_logic_0;
    }
}

void inference_sm::thread_X_0_0_ce1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read())) {
        X_0_0_ce1 = grp_inference_mult_1_84_84_10_s_fu_228_A_0_0_ce1.read();
    } else {
        X_0_0_ce1 = ap_const_logic_0;
    }
}

void inference_sm::thread_X_1_0_address0() {
    X_1_0_address0 = grp_inference_mult_1_84_84_10_s_fu_228_A_1_0_address0.read();
}

void inference_sm::thread_X_1_0_address1() {
    X_1_0_address1 = grp_inference_mult_1_84_84_10_s_fu_228_A_1_0_address1.read();
}

void inference_sm::thread_X_1_0_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read())) {
        X_1_0_ce0 = grp_inference_mult_1_84_84_10_s_fu_228_A_1_0_ce0.read();
    } else {
        X_1_0_ce0 = ap_const_logic_0;
    }
}

void inference_sm::thread_X_1_0_ce1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read())) {
        X_1_0_ce1 = grp_inference_mult_1_84_84_10_s_fu_228_A_1_0_ce1.read();
    } else {
        X_1_0_ce1 = ap_const_logic_0;
    }
}

void inference_sm::thread_X_2_0_address0() {
    X_2_0_address0 = grp_inference_mult_1_84_84_10_s_fu_228_A_2_0_address0.read();
}

void inference_sm::thread_X_2_0_address1() {
    X_2_0_address1 = grp_inference_mult_1_84_84_10_s_fu_228_A_2_0_address1.read();
}

void inference_sm::thread_X_2_0_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read())) {
        X_2_0_ce0 = grp_inference_mult_1_84_84_10_s_fu_228_A_2_0_ce0.read();
    } else {
        X_2_0_ce0 = ap_const_logic_0;
    }
}

void inference_sm::thread_X_2_0_ce1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read())) {
        X_2_0_ce1 = grp_inference_mult_1_84_84_10_s_fu_228_A_2_0_ce1.read();
    } else {
        X_2_0_ce1 = ap_const_logic_0;
    }
}

void inference_sm::thread_X_3_0_address0() {
    X_3_0_address0 = grp_inference_mult_1_84_84_10_s_fu_228_A_3_0_address0.read();
}

void inference_sm::thread_X_3_0_address1() {
    X_3_0_address1 = grp_inference_mult_1_84_84_10_s_fu_228_A_3_0_address1.read();
}

void inference_sm::thread_X_3_0_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read())) {
        X_3_0_ce0 = grp_inference_mult_1_84_84_10_s_fu_228_A_3_0_ce0.read();
    } else {
        X_3_0_ce0 = ap_const_logic_0;
    }
}

void inference_sm::thread_X_3_0_ce1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read())) {
        X_3_0_ce1 = grp_inference_mult_1_84_84_10_s_fu_228_A_3_0_ce1.read();
    } else {
        X_3_0_ce1 = ap_const_logic_0;
    }
}

void inference_sm::thread_ap_done() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_done_reg.read()) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st6_fsm_5.read()) && 
          !esl_seteq<1,1,1>(ap_const_logic_0, grp_inference_softmax_1_10_s_fu_430_ap_done.read())))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void inference_sm::thread_ap_idle() {
    if ((!esl_seteq<1,1,1>(ap_const_logic_1, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void inference_sm::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st6_fsm_5.read()) && 
         !esl_seteq<1,1,1>(ap_const_logic_0, grp_inference_softmax_1_10_s_fu_430_ap_done.read()))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void inference_sm::thread_ap_sig_bdd_25() {
    ap_sig_bdd_25 = esl_seteq<1,1,1>(ap_CS_fsm.read().range(0, 0), ap_const_lv1_1);
}

void inference_sm::thread_ap_sig_bdd_251() {
    ap_sig_bdd_251 = (esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1));
}

void inference_sm::thread_ap_sig_bdd_259() {
    ap_sig_bdd_259 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(1, 1));
}

void inference_sm::thread_ap_sig_bdd_940() {
    ap_sig_bdd_940 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(2, 2));
}

void inference_sm::thread_ap_sig_bdd_947() {
    ap_sig_bdd_947 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(3, 3));
}

void inference_sm::thread_ap_sig_bdd_964() {
    ap_sig_bdd_964 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(4, 4));
}

void inference_sm::thread_ap_sig_bdd_971() {
    ap_sig_bdd_971 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(5, 5));
}

void inference_sm::thread_ap_sig_cseq_ST_st1_fsm_0() {
    if (ap_sig_bdd_25.read()) {
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_0;
    }
}

void inference_sm::thread_ap_sig_cseq_ST_st2_fsm_1() {
    if (ap_sig_bdd_259.read()) {
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_0;
    }
}

void inference_sm::thread_ap_sig_cseq_ST_st3_fsm_2() {
    if (ap_sig_bdd_940.read()) {
        ap_sig_cseq_ST_st3_fsm_2 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st3_fsm_2 = ap_const_logic_0;
    }
}

void inference_sm::thread_ap_sig_cseq_ST_st4_fsm_3() {
    if (ap_sig_bdd_947.read()) {
        ap_sig_cseq_ST_st4_fsm_3 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st4_fsm_3 = ap_const_logic_0;
    }
}

void inference_sm::thread_ap_sig_cseq_ST_st5_fsm_4() {
    if (ap_sig_bdd_964.read()) {
        ap_sig_cseq_ST_st5_fsm_4 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st5_fsm_4 = ap_const_logic_0;
    }
}

void inference_sm::thread_ap_sig_cseq_ST_st6_fsm_5() {
    if (ap_sig_bdd_971.read()) {
        ap_sig_cseq_ST_st6_fsm_5 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st6_fsm_5 = ap_const_logic_0;
    }
}

void inference_sm::thread_argmax_TDATA() {
    argmax_TDATA = grp_inference_softmax_1_10_s_fu_430_argmax_TDATA.read();
}

void inference_sm::thread_argmax_TVALID() {
    argmax_TVALID = grp_inference_softmax_1_10_s_fu_430_argmax_TVALID.read();
}

void inference_sm::thread_grp_inference_add_1_10_s_fu_416_A_0_0_q0() {
    grp_inference_add_1_10_s_fu_416_A_0_0_q0 = T_0_0_q0.read();
}

void inference_sm::thread_grp_inference_add_1_10_s_fu_416_A_1_0_q0() {
    grp_inference_add_1_10_s_fu_416_A_1_0_q0 = T_1_0_q0.read();
}

void inference_sm::thread_grp_inference_add_1_10_s_fu_416_A_2_0_q0() {
    grp_inference_add_1_10_s_fu_416_A_2_0_q0 = T_2_0_q0.read();
}

void inference_sm::thread_grp_inference_add_1_10_s_fu_416_A_3_0_q0() {
    grp_inference_add_1_10_s_fu_416_A_3_0_q0 = T_3_0_q0.read();
}

void inference_sm::thread_grp_inference_add_1_10_s_fu_416_ap_start() {
    grp_inference_add_1_10_s_fu_416_ap_start = grp_inference_add_1_10_s_fu_416_ap_start_ap_start_reg.read();
}

void inference_sm::thread_grp_inference_mult_1_84_84_10_s_fu_228_A_0_0_q0() {
    grp_inference_mult_1_84_84_10_s_fu_228_A_0_0_q0 = X_0_0_q0.read();
}

void inference_sm::thread_grp_inference_mult_1_84_84_10_s_fu_228_A_0_0_q1() {
    grp_inference_mult_1_84_84_10_s_fu_228_A_0_0_q1 = X_0_0_q1.read();
}

void inference_sm::thread_grp_inference_mult_1_84_84_10_s_fu_228_A_1_0_q0() {
    grp_inference_mult_1_84_84_10_s_fu_228_A_1_0_q0 = X_1_0_q0.read();
}

void inference_sm::thread_grp_inference_mult_1_84_84_10_s_fu_228_A_1_0_q1() {
    grp_inference_mult_1_84_84_10_s_fu_228_A_1_0_q1 = X_1_0_q1.read();
}

void inference_sm::thread_grp_inference_mult_1_84_84_10_s_fu_228_A_2_0_q0() {
    grp_inference_mult_1_84_84_10_s_fu_228_A_2_0_q0 = X_2_0_q0.read();
}

void inference_sm::thread_grp_inference_mult_1_84_84_10_s_fu_228_A_2_0_q1() {
    grp_inference_mult_1_84_84_10_s_fu_228_A_2_0_q1 = X_2_0_q1.read();
}

void inference_sm::thread_grp_inference_mult_1_84_84_10_s_fu_228_A_3_0_q0() {
    grp_inference_mult_1_84_84_10_s_fu_228_A_3_0_q0 = X_3_0_q0.read();
}

void inference_sm::thread_grp_inference_mult_1_84_84_10_s_fu_228_A_3_0_q1() {
    grp_inference_mult_1_84_84_10_s_fu_228_A_3_0_q1 = X_3_0_q1.read();
}

void inference_sm::thread_grp_inference_mult_1_84_84_10_s_fu_228_ap_start() {
    grp_inference_mult_1_84_84_10_s_fu_228_ap_start = grp_inference_mult_1_84_84_10_s_fu_228_ap_start_ap_start_reg.read();
}

void inference_sm::thread_grp_inference_softmax_1_10_s_fu_430_A_0_0_q0() {
    grp_inference_softmax_1_10_s_fu_430_A_0_0_q0 = S_0_0_q0.read();
}

void inference_sm::thread_grp_inference_softmax_1_10_s_fu_430_A_1_0_q0() {
    grp_inference_softmax_1_10_s_fu_430_A_1_0_q0 = S_1_0_q0.read();
}

void inference_sm::thread_grp_inference_softmax_1_10_s_fu_430_A_2_0_q0() {
    grp_inference_softmax_1_10_s_fu_430_A_2_0_q0 = S_2_0_q0.read();
}

void inference_sm::thread_grp_inference_softmax_1_10_s_fu_430_A_3_0_q0() {
    grp_inference_softmax_1_10_s_fu_430_A_3_0_q0 = S_3_0_q0.read();
}

void inference_sm::thread_grp_inference_softmax_1_10_s_fu_430_ap_start() {
    grp_inference_softmax_1_10_s_fu_430_ap_start = grp_inference_softmax_1_10_s_fu_430_ap_start_ap_start_reg.read();
}

void inference_sm::thread_grp_inference_softmax_1_10_s_fu_430_argmax_TREADY() {
    grp_inference_softmax_1_10_s_fu_430_argmax_TREADY = argmax_TREADY.read();
}

void inference_sm::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if (!ap_sig_bdd_251.read()) {
                ap_NS_fsm = ap_ST_st2_fsm_1;
            } else {
                ap_NS_fsm = ap_ST_st1_fsm_0;
            }
            break;
        case 2 : 
            if (!esl_seteq<1,1,1>(ap_const_logic_0, grp_inference_mult_1_84_84_10_s_fu_228_ap_done.read())) {
                ap_NS_fsm = ap_ST_st3_fsm_2;
            } else {
                ap_NS_fsm = ap_ST_st2_fsm_1;
            }
            break;
        case 4 : 
            ap_NS_fsm = ap_ST_st4_fsm_3;
            break;
        case 8 : 
            if (!esl_seteq<1,1,1>(ap_const_logic_0, grp_inference_add_1_10_s_fu_416_ap_done.read())) {
                ap_NS_fsm = ap_ST_st5_fsm_4;
            } else {
                ap_NS_fsm = ap_ST_st4_fsm_3;
            }
            break;
        case 16 : 
            ap_NS_fsm = ap_ST_st6_fsm_5;
            break;
        case 32 : 
            if (!esl_seteq<1,1,1>(ap_const_logic_0, grp_inference_softmax_1_10_s_fu_430_ap_done.read())) {
                ap_NS_fsm = ap_ST_st1_fsm_0;
            } else {
                ap_NS_fsm = ap_ST_st6_fsm_5;
            }
            break;
        default : 
            ap_NS_fsm =  (sc_lv<6>) ("XXXXXX");
            break;
    }
}

}

