// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.4
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ==============================================================

#ifndef __inference_conv2d_2_f2_2_4_4_H__
#define __inference_conv2d_2_f2_2_4_4_H__


#include <systemc>
using namespace sc_core;
using namespace sc_dt;




#include <iostream>
#include <fstream>

struct inference_conv2d_2_f2_2_4_4_ram : public sc_core::sc_module {

  static const unsigned DataWidth = 32;
  static const unsigned AddressRange = 16;
  static const unsigned AddressWidth = 4;

//latency = 1
//input_reg = 1
//output_reg = 0
sc_core::sc_in <sc_lv<AddressWidth> > address0;
sc_core::sc_in <sc_logic> ce0;
sc_core::sc_out <sc_lv<DataWidth> > q0;
sc_core::sc_in<sc_logic> reset;
sc_core::sc_in<bool> clk;


sc_lv<DataWidth> ram[AddressRange];


   SC_CTOR(inference_conv2d_2_f2_2_4_4_ram) {
        ram[0] = "0b10111101100000111111100011001110";
        ram[1] = "0b10111100011011011010101011111110";
        ram[2] = "0b00111100111010010000111111111001";
        ram[3] = "0b00111100111011111111100000010101";
        ram[4] = "0b00111101110110001110011101011000";
        ram[5] = "0b10111101100011101001011011010001";
        ram[6] = "0b00111110100001101110011001010100";
        ram[7] = "0b00111101001110101010010101001101";
        ram[8] = "0b10111101000111110111011001101101";
        ram[9] = "0b00111100110110011101001101000110";
        ram[10] = "0b00111101110100100011111101101000";
        ram[11] = "0b00111100100110101010001101001111";
        ram[12] = "0b00111110000101110100110100010110";
        ram[13] = "0b00111101011101110100010110110010";
        ram[14] = "0b00111101011011011000010100100100";
        ram[15] = "0b10111011110011000111100111101100";


SC_METHOD(prc_write_0);
  sensitive<<clk.pos();
   }


void prc_write_0()
{
    if (ce0.read() == sc_dt::Log_1) 
    {
            if(address0.read().is_01() && address0.read().to_uint()<AddressRange)
              q0 = ram[address0.read().to_uint()];
            else
              q0 = sc_lv<DataWidth>();
    }
}


}; //endmodule


SC_MODULE(inference_conv2d_2_f2_2_4_4) {


static const unsigned DataWidth = 32;
static const unsigned AddressRange = 16;
static const unsigned AddressWidth = 4;

sc_core::sc_in <sc_lv<AddressWidth> > address0;
sc_core::sc_in<sc_logic> ce0;
sc_core::sc_out <sc_lv<DataWidth> > q0;
sc_core::sc_in<sc_logic> reset;
sc_core::sc_in<bool> clk;


inference_conv2d_2_f2_2_4_4_ram* meminst;


SC_CTOR(inference_conv2d_2_f2_2_4_4) {
meminst = new inference_conv2d_2_f2_2_4_4_ram("inference_conv2d_2_f2_2_4_4_ram");
meminst->address0(address0);
meminst->ce0(ce0);
meminst->q0(q0);

meminst->reset(reset);
meminst->clk(clk);
}
~inference_conv2d_2_f2_2_4_4() {
    delete meminst;
}


};//endmodule
#endif
